/**
 * @file QuizBank.js
 * Question Repository, Procedural Exam Generator, and LaTeX/Print Exporter
 * for Discrete Mathematics & Logic Education.
 * 
 * Fully covers all 5 Curriculum Pillars / Chapters directly from the university slides:
 * - Chapter 1: Propositional & Predicate Logic, Inference Rules & Quantifiers
 * - Chapter 2: Boolean Algebra, Normal Forms (DNF/CNF), Digital Logic Circuits & Karnaugh Maps
 * - Chapter 3: Sets, Mappings, Counting Principles, Permutations, Combinations, Pigeonhole & Recurrence Relations
 * - Chapter 4: Binary Relations, Equivalence, Modulo, POSET, Hasse Diagrams & Closures
 * - Chapter 5: Graph Theory, Degree, Handshaking, Euler, Hamilton, Trees, Kruskal, Prim & Dijkstra
 */

export const QUIZ_TOPICS = {
  ALL: 'all',
  LOGIC: 'logic',
  BOOLEAN: 'boolean',
  COUNTING: 'counting',
  RELATION: 'relation',
  GRAPH: 'graph',
};

export const QUIZ_DIFFICULTIES = {
  ALL: 'all',
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
};

/**
 * Curated Question Bank covering university-level Discrete Mathematics across all chapters (125 Questions total).
 * 100% aligned with lecture slides. Logic notation: AND = *, OR = +, NOT = ¬.
 */
export const STATIC_QUESTION_BANK = [
  // =========================================================================
  // CHƯƠNG 1: CƠ SỞ LOGIC VÀ SUY LUẬN (25 CÂU)
  // =========================================================================
  {
    id: 'logic_q01',
    topic: 'logic',
    topicName: 'Phép kéo theo Logic',
    difficulty: 'easy',
    question: 'Cho hai mệnh đề p = Đúng (1) và q = Sai (0). Mệnh đề kéo theo (p → q) có giá trị chân trị là gì?',
    options: [
      { id: 'A', text: '1 (Đúng)' },
      { id: 'B', text: '0 (Sai)' },
      { id: 'C', text: 'Không xác định được' },
      { id: 'D', text: 'Cả 1 và 0 đều đúng' },
    ],
    correctId: 'B',
    explanation: 'Theo định nghĩa phép kéo theo trong slide Chương 1 trang 8-9, p → q chỉ nhận giá trị SAI duy nhất khi tiền đề p Đúng (1) và kết luận q Sai (0). Do đó 1 → 0 = 0.',
    actionLink: { view: 'logic', expression: 'p → q' },
  },
  {
    id: 'logic_q02',
    topic: 'logic',
    topicName: 'Hằng đúng & Hằng sai',
    difficulty: 'easy',
    question: 'Biểu thức logic p + ¬p (Luật bù / Triệt tam) thuộc loại mệnh đề nào sau đây?',
    options: [
      { id: 'A', text: 'Mâu thuẫn / Hằng sai (Contradiction)' },
      { id: 'B', text: 'Tiếp liên / Thỏa được (Contingency)' },
      { id: 'C', text: 'Hằng đúng (Tautology)' },
      { id: 'D', text: 'Không thể phân loại' },
    ],
    correctId: 'C',
    explanation: 'Theo slide Chương 1 trang 17, một dạng mệnh đề luôn nhận giá trị Đúng (1) với mọi trường hợp của các biến mệnh đề được gọi là Hằng đúng (Tautology). Với mọi p: p + ¬p = 1.',
    actionLink: { view: 'logic', expression: 'p + ¬p' },
  },
  {
    id: 'logic_q03',
    topic: 'logic',
    topicName: 'Luật De Morgan',
    difficulty: 'medium',
    question: 'Theo luật De Morgan trong slide Chương 1, phủ định của mệnh đề hội ¬(p * q) tương đương logic với biểu thức nào?',
    options: [
      { id: 'A', text: '¬p * ¬q' },
      { id: 'B', text: '¬p + ¬q' },
      { id: 'C', text: 'p + q' },
      { id: 'D', text: '¬p → q' },
    ],
    correctId: 'B',
    explanation: 'Theo luật De Morgan trong slide Chương 1 trang 22: Phủ định của một hội bằng tuyển các phủ định: ¬(p * q) ≡ ¬p + ¬q.',
    actionLink: { view: 'logic', expression: '¬(p * q) ↔ (¬p + ¬q)' },
  },
  {
    id: 'logic_q04',
    topic: 'logic',
    topicName: 'Phép tương đương Logic',
    difficulty: 'easy',
    question: 'Phép tương đương logic (p ↔ q) nhận giá trị Đúng (1) trong trường hợp nào?',
    options: [
      { id: 'A', text: 'Chỉ khi cả p và q đều nhận giá trị Đúng (1)' },
      { id: 'B', text: 'Chỉ khi cả p và q đều nhận giá trị Sai (0)' },
      { id: 'C', text: 'Khi p và q có cùng giá trị chân trị (cùng Đúng hoặc cùng Sai)' },
      { id: 'D', text: 'Khi ít nhất một trong hai mệnh đề nhận giá trị Đúng' },
    ],
    correctId: 'C',
    explanation: 'Theo bảng chân trị phép tương đương trong slide Chương 1 trang 10: p ↔ q nhận giá trị Đúng khi và chỉ khi p và q có cùng chân trị (cùng bằng 1 hoặc cùng bằng 0).',
    actionLink: { view: 'logic', expression: 'p ↔ q' },
  },
  {
    id: 'logic_q05',
    topic: 'logic',
    topicName: 'Phép hội Logic',
    difficulty: 'easy',
    question: 'Phép hội logic giữa hai mệnh đề p và q (ký hiệu p * q) nhận giá trị Đúng (1) khi nào?',
    options: [
      { id: 'A', text: 'Cả hai mệnh đề p và q đều nhận giá trị Đúng (1)' },
      { id: 'B', text: 'Ít nhất một trong hai mệnh đề p hoặc q nhận giá trị Đúng (1)' },
      { id: 'C', text: 'Cả hai mệnh đề p và q đều nhận giá trị Sai (0)' },
      { id: 'D', text: 'Khi tiền đề p Đúng và kết luận q Sai' },
    ],
    correctId: 'A',
    explanation: 'Theo bảng chân trị phép hội trong slide Chương 1 trang 6: p * q chỉ nhận giá trị Đúng duy nhất khi cả hai mệnh đề p = 1 và q = 1.',
    actionLink: { view: 'logic', expression: 'p * q' },
  },
  {
    id: 'logic_q06',
    topic: 'logic',
    topicName: 'Khái niệm Mệnh đề',
    difficulty: 'easy',
    question: 'Trong các câu sau đây, câu nào là một Mệnh đề logic theo định nghĩa giáo trình?',
    options: [
      { id: 'A', text: 'Hôm nay em đẹp quá!' },
      { id: 'B', text: 'Đại học CNTT trực thuộc ĐHQG TP.HCM.' },
      { id: 'C', text: 'Hôm nay là ngày thứ mấy?' },
      { id: 'D', text: 'Hãy giải bài tập này cẩn thận!' },
    ],
    correctId: 'B',
    explanation: 'Theo định nghĩa trang 3 slide Chương 1: Mệnh đề là khẳng định có giá trị chân lý xác định (đúng hoặc sai). Câu hỏi, câu cảm thán, câu cầu khiến không là mệnh đề. Câu B là khẳng định đúng.',
  },
  {
    id: 'logic_q07',
    topic: 'logic',
    topicName: 'Luật tương đương kéo theo',
    difficulty: 'medium',
    question: 'Mệnh đề kéo theo p → q tương đương logic với dạng mệnh đề nào sau đây (luật về phép kéo theo)?',
    options: [
      { id: 'A', text: 'p * ¬q' },
      { id: 'B', text: '¬p + q' },
      { id: 'C', text: '¬p * q' },
      { id: 'D', text: 'p + ¬q' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 18 và 22: Luật kéo theo khẳng định p → q ≡ ¬p + q.',
    actionLink: { view: 'logic', expression: '(p → q) ↔ (¬p + q)' },
  },
  {
    id: 'logic_q08',
    topic: 'logic',
    topicName: 'Mệnh đề phản đảo',
    difficulty: 'easy',
    question: 'Mệnh đề phản đảo của mệnh đề kéo theo p → q là mệnh đề nào sau đây?',
    options: [
      { id: 'A', text: '¬q → ¬p' },
      { id: 'B', text: 'q → p' },
      { id: 'C', text: '¬p → ¬q' },
      { id: 'D', text: '¬p → q' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 11: Mệnh đề phản đảo của p → q là ¬q → ¬p và hai mệnh đề này luôn tương đương logic với nhau (p → q ≡ ¬q → ¬p).',
    actionLink: { view: 'logic', expression: '(p → q) ↔ (¬q → ¬p)' },
  },
  {
    id: 'logic_q09',
    topic: 'logic',
    topicName: 'Luật phân phối Logic',
    difficulty: 'medium',
    question: 'Theo luật phân phối trong slide Chương 1, biểu thức p * (q + r) tương đương logic với biểu thức nào?',
    options: [
      { id: 'A', text: '(p * q) + (p * r)' },
      { id: 'B', text: '(p + q) * (p + r)' },
      { id: 'C', text: '(p * q) * r' },
      { id: 'D', text: '(p + q) + r' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 22: Luật phân phối phép hội đối với phép tuyển: p * (q + r) ≡ (p * q) + (p * r).',
    actionLink: { view: 'logic', expression: '(p * (q + r)) ↔ ((p * q) + (p * r))' },
  },
  {
    id: 'logic_q10',
    topic: 'logic',
    topicName: 'Luật hấp thu Logic',
    difficulty: 'medium',
    question: 'Theo luật hấp thu trong slide Chương 1, biểu thức p * (p + q) tương đương logic với biểu thức nào?',
    options: [
      { id: 'A', text: 'q' },
      { id: 'B', text: 'p' },
      { id: 'C', text: 'p * q' },
      { id: 'D', text: '1' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 22: Luật hấp thu khẳng định p * (p + q) ≡ p và p + (p * q) ≡ p.',
    actionLink: { view: 'logic', expression: 'p * (p + q) ↔ p' },
  },
  {
    id: 'logic_q11',
    topic: 'logic',
    topicName: 'Vị từ và Lượng từ với mọi',
    difficulty: 'easy',
    question: 'Mệnh đề chứa lượng từ với mọi "∀x ∈ D, P(x)" nhận giá trị Đúng khi nào?',
    options: [
      { id: 'A', text: 'Khi tồn tại ít nhất một phần tử x₀ ∈ D làm cho P(x₀) đúng' },
      { id: 'B', text: 'Khi có hơn một nửa số phần tử trong D làm cho P(x) đúng' },
      { id: 'C', text: 'Khi P(x) đúng với tất cả các phần tử x thuộc miền xác định D' },
      { id: 'D', text: 'Khi P(x) chỉ đúng với phần tử đầu tiên của D' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 1 trang 44-46: Lượng từ với mọi ∀x P(x) khẳng định tính chất P đúng cho mọi giá trị của biến x trong miền xác định D.',
  },
  {
    id: 'logic_q12',
    topic: 'logic',
    topicName: 'Lượng từ tồn tại',
    difficulty: 'easy',
    question: 'Mệnh đề chứa lượng từ tồn tại "∃x ∈ D, P(x)" nhận giá trị Sai khi nào?',
    options: [
      { id: 'A', text: 'Khi có ít nhất một phần tử x ∈ D làm cho P(x) sai' },
      { id: 'B', text: 'Khi P(x) nhận giá trị Sai với tất cả các phần tử x thuộc D' },
      { id: 'C', text: 'Khi tập D là tập vô hạn' },
      { id: 'D', text: 'Khi P(x) nhận giá trị Đúng với ít nhất 1 phần tử' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 47-49: ∃x P(x) chỉ sai khi không tìm thấy bất kỳ phần tử nào làm cho P(x) đúng, nghĩa là P(x) sai với mọi x ∈ D.',
  },
  {
    id: 'logic_q13',
    topic: 'logic',
    topicName: 'Phủ định lượng từ với mọi',
    difficulty: 'medium',
    question: 'Phủ định của mệnh đề chứa lượng từ "∀x ∈ ℝ, x² ≥ 0" là mệnh đề nào sau đây?',
    options: [
      { id: 'A', text: '∃x ∈ ℝ, x² < 0' },
      { id: 'B', text: '∀x ∈ ℝ, x² < 0' },
      { id: 'C', text: '∃x ∈ ℝ, x² ≤ 0' },
      { id: 'D', text: '∀x ∈ ℝ, x² ≤ 0' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 50: Theo quy tắc phủ định lượng từ: ¬(∀x P(x)) ≡ ∃x ¬P(x). Phủ định của x² ≥ 0 là x² < 0, do đó ta được ∃x ∈ ℝ, x² < 0.',
  },
  {
    id: 'logic_q14',
    topic: 'logic',
    topicName: 'Phủ định lượng từ tồn tại',
    difficulty: 'medium',
    question: 'Theo quy tắc phủ định lượng từ trong slide Chương 1, biểu thức ¬(∃x P(x)) tương đương logic với dạng nào?',
    options: [
      { id: 'A', text: '∃x ¬P(x)' },
      { id: 'B', text: '¬(∀x P(x))' },
      { id: 'C', text: '∃x P(x)' },
      { id: 'D', text: '∀x ¬P(x)' },
    ],
    correctId: 'D',
    explanation: 'Slide Chương 1 trang 50: Phủ định của tồn tại là với mọi phủ định: ¬(∃x P(x)) ≡ ∀x ¬P(x).',
  },
  {
    id: 'logic_q15',
    topic: 'logic',
    topicName: 'Qui tắc khẳng định (Modus Ponens)',
    difficulty: 'easy',
    question: 'Qui tắc khẳng định (Modus Ponens) trong slide Chương 1 trang 31 biểu diễn dạng suy luận nào sau đây?',
    options: [
      { id: 'A', text: 'Tiền đề: p → q và p. Kết luận: q' },
      { id: 'B', text: 'Tiền đề: p → q và ¬q. Kết luận: ¬p' },
      { id: 'C', text: 'Tiền đề: p → q và q → r. Kết luận: p → r' },
      { id: 'D', text: 'Tiền đề: p và q. Kết luận: p * q' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 31: 1. Qui tắc khẳng định (Modus Ponens): [(p → q) * p] → q. Giả thiết p → q và p, kết luận q.',
    actionLink: { view: 'logic', expression: '((p → q) * p) → q' },
  },
  {
    id: 'logic_q16',
    topic: 'logic',
    topicName: 'Qui tắc khẳng định (dạng tuyển)',
    difficulty: 'medium',
    question: 'Trong slide Chương 1 trang 31, qui tắc suy diễn [(p + q) * ¬p] → q được xếp vào qui tắc nào sau đây?',
    options: [
      { id: 'A', text: 'Qui tắc phủ định (Modus Tollens)' },
      { id: 'B', text: 'Qui tắc khẳng định (Modus Ponens)' },
      { id: 'C', text: 'Qui tắc mâu thuẫn' },
      { id: 'D', text: 'Qui tắc phản chứng' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 31: Qui tắc khẳng định (Modus Ponens) bao gồm 2 mô hình: [(p → q) * p] → q và [(p + q) * ¬p] → q. Ví dụ trong slide: An hay Tuấn ăn cua biển; Tuấn ăn chay; Suy ra An ăn cua biển.',
    actionLink: { view: 'logic', expression: '((p + q) * ¬p) → q' },
  },
  {
    id: 'logic_q17',
    topic: 'logic',
    topicName: 'Qui tắc phủ định (Modus Tollens)',
    difficulty: 'medium',
    question: 'Cho suy luận: "Nếu Hùng chăm học thì Hùng đạt môn Toán rời rạc. Hùng không đạt môn Toán rời rạc. Suy ra Hùng không chăm học." Đây là ví dụ áp dụng quy tắc suy diễn nào trong slide Chương 1 trang 32?',
    options: [
      { id: 'A', text: 'Qui tắc khẳng định (Modus Ponens)' },
      { id: 'B', text: 'Qui tắc phủ định (Modus Tollens)' },
      { id: 'C', text: 'Qui tắc tam đoạn luận' },
      { id: 'D', text: 'Qui tắc mâu thuẫn' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 32: 2. Qui tắc phủ định (Modus Tollens): [(p → q) * ¬q] → ¬p. Từ p → q và ¬q suy ra ¬p.',
    actionLink: { view: 'logic', expression: '((p → q) * ¬q) → ¬p' },
  },
  {
    id: 'logic_q18',
    topic: 'logic',
    topicName: 'Qui tắc tam đoạn luận',
    difficulty: 'medium',
    question: 'Qui tắc tam đoạn luận trong slide Chương 1 trang 33 khẳng định hằng đúng nào sau đây?',
    options: [
      { id: 'A', text: '[(p → q) * (q → r)] → (p → r)' },
      { id: 'B', text: '[(p → q) * p] → q' },
      { id: 'C', text: '[(p → q) * ¬q] → ¬p' },
      { id: 'D', text: '[(p + q) * ¬p] → q' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 33: 3. Qui tắc tam đoạn luận: [(p → q) * (q → r)] → (p → r). Ví dụ trong slide: Nếu trời mưa thì đường ướt; Nếu đường ướt thì đường trơn; Suy ra nếu trời mưa thì đường trơn.',
    actionLink: { view: 'logic', expression: '((p → q) * (q → r)) → (p → r)' },
  },
  {
    id: 'logic_q19',
    topic: 'logic',
    topicName: 'Qui tắc mâu thuẫn',
    difficulty: 'medium',
    question: 'Theo slide Chương 1 trang 34, Qui tắc mâu thuẫn được mô tả bởi sự tương đương nào sau đây?',
    options: [
      { id: 'A', text: '(p → q) ≡ (¬p + q)' },
      { id: 'B', text: '(p → q) ≡ [(p * q) → 1]' },
      { id: 'C', text: '(p → q) ≡ [(p * ¬q) → 0]' },
      { id: 'D', text: '(p → q) ≡ (¬q → ¬p)' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 1 trang 34: 4. Qui tắc mâu thuẫn: (p → q) ≡ [(p * ¬q) → 0]. Nếu thêm ¬q vào giả thiết p mà dẫn tới mâu thuẫn (0) thì q là hệ quả logic của p.',
    actionLink: { view: 'logic', expression: '(p → q) ↔ ((p * ¬q) → 0)' },
  },
  {
    id: 'logic_q20',
    topic: 'logic',
    topicName: 'Qui tắc phản chứng',
    difficulty: 'hard',
    question: 'Qui tắc phản chứng trong slide Chương 1 trang 35 khẳng định equivalence logic nào sau đây?',
    options: [
      { id: 'A', text: '[(p₁ * p₂ * ... * pₙ) → q] ⇔ [(p₁ * p₂ * ... * pₙ) → ¬q]' },
      { id: 'B', text: '[(p₁ * p₂ * ... * pₙ) → q] ⇔ [(p₁ * p₂ * ... * pₙ * ¬q) → 0]' },
      { id: 'C', text: '[(p₁ + p₂ + ... + pₙ) → q] ⇔ [(p₁ * p₂ * ... * pₙ) → 0]' },
      { id: 'D', text: '[(p₁ * p₂ * ... * pₙ) → q] ⇔ (q → 0)' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 35: 5. Qui tắc phản chứng: [(p₁ * p₂ * ... * pₙ) → q] ⇔ [(p₁ * p₂ * ... * pₙ * ¬q) → 0]. Giả sử phủ định kết luận (thêm ¬q vào giả thiết) và suy ra mâu thuẫn 0.',
  },
  {
    id: 'logic_q21',
    topic: 'logic',
    topicName: 'Qui tắc chứng minh theo trường hợp',
    difficulty: 'medium',
    question: 'Qui tắc chứng minh theo trường hợp trong slide Chương 1 trang 36 biểu diễn dưới dạng hằng đúng nào?',
    options: [
      { id: 'A', text: '[(p → r) * (q → r)] → [(p + q) → r]' },
      { id: 'B', text: '[(p → r) + (q → r)] → [(p * q) → r]' },
      { id: 'C', text: '[(p → q) * (q → r)] → (p → r)' },
      { id: 'D', text: '[(p + q) * ¬p] → q' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 36: 5. Qui tắc chứng minh theo trường hợp: [(p → r) * (q → r)] → [(p + q) → r].',
  },
  {
    id: 'logic_q22',
    topic: 'logic',
    topicName: 'Phản ví dụ trong suy luận',
    difficulty: 'easy',
    question: 'Để chứng minh một phép suy luận là SAI (hoặc không phải là một hằng đúng), phương pháp đơn giản nhất theo slide Chương 1 trang 36 là gì?',
    options: [
      { id: 'A', text: 'Lập bảng chân trị đầy đủ cho tất cả 2ⁿ trường hợp' },
      { id: 'B', text: 'Dùng quy tắc phản chứng đưa về mâu thuẫn' },
      { id: 'C', text: 'Chỉ ra một phản ví dụ (một bộ giá trị chân trị mà giả thiết đúng nhưng kết luận sai)' },
      { id: 'D', text: 'Biến đổi biểu thức về dạng nối rời chính tắc' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 1 trang 36 mục 6: Phản ví dụ: Để chứng minh một phép suy luận là sai hay không là một hằng đúng, ta chỉ cần chỉ ra một phản ví dụ.',
  },
  {
    id: 'logic_q23',
    topic: 'logic',
    topicName: 'Bài tập suy luận (Slide trang 40)',
    difficulty: 'hard',
    question: 'Xét suy luận trong bài tập slide Chương 1 trang 40: "Nếu Kiệt đi chơi thì Kiệt không học môn toán rời rạc. Kiệt không học môn toán rời rạc thì Kiệt thi trượt toán rời rạc. Mà Kiệt lại đi chơi. Vậy Kiệt thi trượt toán rời rạc." Suy luận này có logic không và áp dụng quy tắc nào?',
    options: [
      { id: 'A', text: 'Hợp logic, áp dụng Qui tắc tam đoạn luận kết hợp Qui tắc khẳng định (Modus Ponens)' },
      { id: 'B', text: 'Không hợp logic, vì phạm lỗi ngụy biện phủ định tiền đề' },
      { id: 'C', text: 'Hợp logic, áp dụng Qui tắc phủ định (Modus Tollens)' },
      { id: 'D', text: 'Không hợp logic, vì thiếu dữ kiện về điểm chuyên cần' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 40: Đặt p = Kiệt đi chơi, q = Kiệt không học, r = Kiệt thi trượt. Ta có p → q và q → r, theo Qui tắc tam đoạn luận suy ra p → r. Kết hợp với tiền đề p (Kiệt đi chơi), theo Modus Ponens suy ra r (Kiệt thi trượt). Do đó suy luận hoàn toàn hợp logic.',
  },
  {
    id: 'logic_q24',
    topic: 'logic',
    topicName: 'Bài tập điểm danh suy luận (Slide trang 42)',
    difficulty: 'hard',
    question: 'Xét bài tập điểm danh slide Chương 1 trang 42 về Phi Hùng, Phú Huy và cô Thị Thanh: từ giả thiết "Cô Thị Thanh không nhận được lời than phiền", kết luận nào được rút ra một cách hợp logic?',
    options: [
      { id: 'A', text: 'Phi Hùng đi làm về muộn và Phú Huy thường xuyên vắng nhà' },
      { id: 'B', text: 'Phi Hùng đi làm về sớm và Phú Huy rất ít khi vắng nhà' },
      { id: 'C', text: 'Cô Thị Thanh không phải là bạn của vợ họ' },
      { id: 'D', text: 'Chưa đủ dữ kiện để đưa ra kết luận hợp logic' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 1 trang 42: Vợ Hùng hoặc vợ Huy giận dữ → Thị Thanh nhận lời than phiền. Vì Thị Thanh không nhận lời than phiền, theo Modus Tollens suy ra cả vợ Hùng và vợ Huy đều không giận dữ. Tiếp tục theo Modus Tollens với hai mệnh đề kéo theo ban đầu, suy ra Phi Hùng về sớm và Phú Huy ít khi vắng nhà.',
  },
  {
    id: 'logic_q25',
    topic: 'logic',
    topicName: 'Biểu thức Hằng sai / Mâu thuẫn',
    difficulty: 'easy',
    question: 'Biểu thức logic nào sau đây là một Hằng sai / Mâu thuẫn (Contradiction)?',
    options: [
      { id: 'A', text: 'p * ¬p' },
      { id: 'B', text: 'p + ¬p' },
      { id: 'C', text: 'p → p' },
      { id: 'D', text: 'p ↔ p' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 1 trang 17: Mâu thuẫn là dạng mệnh đề luôn nhận giá trị Sai (0). Biểu thức p * ¬p luôn bằng 0 vì một mệnh đề và phủ định của nó không thể cùng đúng.',
    actionLink: { view: 'logic', expression: 'p * ¬p' },
  },

  // =========================================================================
  // CHƯƠNG 2: ĐẠI SỐ BOOLE VÀ MẠCH LOGIC (25 CÂU)
  // =========================================================================
  {
    id: 'bool_q01',
    topic: 'boolean',
    topicName: 'Khái niệm Đại số Boole',
    difficulty: 'easy',
    question: 'Theo định nghĩa slide Chương 2 trang 3, Đại số Boole đưa ra các phép toán và quy tắc làm việc trên tập hợp nào sau đây?',
    options: [
      { id: 'A', text: 'Tập nhị phân {0, 1}' },
      { id: 'B', text: 'Tập số tự nhiên ℕ' },
      { id: 'C', text: 'Tập số nguyên ℤ' },
      { id: 'D', text: 'Tập số thực ℝ' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 3: Đại số Boole đưa ra các phép toán và quy tắc làm việc với tập {0, 1}. Trong mạch điện máy tính và các dụng cụ điện tử, các mạch được nghiên cứu bằng cách dùng tập này.',
  },
  {
    id: 'bool_q02',
    topic: 'boolean',
    topicName: 'Thứ tự ưu tiên phép toán Boole',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 5, thứ tự thực hiện đúng của các phép toán Boole từ ưu tiên cao đến thấp là gì?',
    options: [
      { id: 'A', text: 'Phép lấy tổng (+) → Phép lấy tích (*) → Lấy phần bù (¬)' },
      { id: 'B', text: 'Lấy phần bù (¬) → Phép lấy tích (*) → Phép lấy tổng (+)' },
      { id: 'C', text: 'Phép lấy tích (*) → Lấy phần bù (¬) → Phép lấy tổng (+)' },
      { id: 'D', text: 'Các phép toán có độ ưu tiên ngang nhau và thực hiện từ trái sang phải' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 5 quy định thứ tự ưu tiên: 1. Lấy phần bù; 2. Phép lấy tích; 3. Phép lấy tổng.',
  },
  {
    id: 'bool_q03',
    topic: 'boolean',
    topicName: 'Tính toán giá trị biểu thức Boole',
    difficulty: 'easy',
    question: 'Trong slide Chương 2 trang 5, giá trị của phép tính Boole (1 * 0) + (0 + 1) bằng bao nhiêu?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '2' },
      { id: 'C', text: '1' },
      { id: 'D', text: 'Không xác định' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 2 trang 5: (1 * 0) = 0 và (0 + 1) = 1. Khi đó 0 + 1 = 1.',
  },
  {
    id: 'bool_q04',
    topic: 'boolean',
    topicName: 'Luật phần bù Boole',
    difficulty: 'easy',
    question: 'Trong đại số Boole, luật phần bù khẳng định đẳng thức nào sau đây là đúng với mọi x ∈ {0, 1}?',
    options: [
      { id: 'A', text: 'x + ¬x = 1 và x * ¬x = 0' },
      { id: 'B', text: 'x + ¬x = 0 và x * ¬x = 1' },
      { id: 'C', text: 'x + ¬x = x' },
      { id: 'D', text: 'x * ¬x = x' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 4-7: Với x = 1 thì ¬x = 0 ⇒ 1 + 0 = 1, 1 * 0 = 0. Với x = 0 thì ¬x = 1 ⇒ 0 + 1 = 1, 0 * 1 = 0.',
  },
  {
    id: 'bool_q05',
    topic: 'boolean',
    topicName: 'Luật nuốt và Thống trị',
    difficulty: 'easy',
    question: 'Theo các quy tắc của đại số Boole, kết quả của hai phép toán x + 1 và x * 0 lần lượt là:',
    options: [
      { id: 'A', text: 'x và x' },
      { id: 'B', text: '0 và 1' },
      { id: 'C', text: 'x và 0' },
      { id: 'D', text: '1 và 0' },
    ],
    correctId: 'D',
    explanation: 'Slide Chương 2 trang 4: Trong tổng Bool, bất kỳ phần tử nào cộng với 1 đều bằng 1 (x + 1 = 1). Trong tích Bool, bất kỳ phần tử nào nhân với 0 đều bằng 0 (x * 0 = 0).',
  },
  {
    id: 'bool_q06',
    topic: 'boolean',
    topicName: 'Luật lũy đẳng Boole',
    difficulty: 'easy',
    question: 'Trong đại số Boole, quy tắc lũy đẳng (Idempotent laws) khẳng định:',
    options: [
      { id: 'A', text: 'x + x = 2x và x * x = x²' },
      { id: 'B', text: 'x + x = x và x * x = x' },
      { id: 'C', text: 'x + x = 1 và x * x = 0' },
      { id: 'D', text: 'x + x = 0 và x * x = 1' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 7: Trong đại số Boole tập {0, 1}: 1 + 1 = 1, 0 + 0 = 0 nên x + x = x; tương tự 1 * 1 = 1, 0 * 0 = 0 nên x * x = x.',
  },
  {
    id: 'bool_q07',
    topic: 'boolean',
    topicName: 'Luật hấp thu Boole',
    difficulty: 'medium',
    question: 'Theo luật hấp thu trong đại số Boole, dạng biểu thức thu gọn của x + (x * y) là:',
    options: [
      { id: 'A', text: 'x' },
      { id: 'B', text: 'y' },
      { id: 'C', text: 'x * y' },
      { id: 'D', text: '1' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 7: x + (x * y) = x * 1 + x * y = x * (1 + y) = x * 1 = x.',
  },
  {
    id: 'bool_q08',
    topic: 'boolean',
    topicName: 'Nguyên lý đối ngẫu Boole',
    difficulty: 'medium',
    question: 'Theo nguyên lý đối ngẫu (Duality Principle) trong đại số Boole, biểu thức đối ngẫu của x + (y * z) được tạo thành bằng cách:',
    options: [
      { id: 'A', text: 'Giữ nguyên phép toán và đổi x thành ¬x' },
      { id: 'B', text: 'Đổi + thành * và giữ nguyên *' },
      { id: 'C', text: 'Đổi dấu + thành * và đổi dấu * thành +, tức là x * (y + z)' },
      { id: 'D', text: 'Lấy phủ định toàn bộ biểu thức ¬(x + y * z)' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 2 trang 8: Nguyên lý đối ngẫu: thay thế phép + bởi * và ngược lại, thay 0 bởi 1 và ngược lại. Do đó x + (y * z) đối ngẫu là x * (y + z).',
  },
  {
    id: 'bool_q09',
    topic: 'boolean',
    topicName: 'Khai triển DNF (Tổng các tích / Minterm)',
    difficulty: 'medium',
    question: 'Theo slide Chương 2 trang 9-14, dạng nối rời chính tắc (Disjunctive Normal Form - DNF / Sum of Minterms) của hàm Boole là:',
    options: [
      { id: 'A', text: 'Tích của các tổng cơ bản (Maxterms)' },
      { id: 'B', text: 'Tổng của các tích cơ bản (Minterms), trong đó mỗi minterm nhận giá trị 1 tại đúng một bộ giá trị biến' },
      { id: 'C', text: 'Biểu thức chỉ chứa cổng NAND' },
      { id: 'D', text: 'Dạng tối thiểu hóa hoàn toàn của hàm Boole' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 9-14: Khai triển hàm Boole dưới dạng tổng các tích (SOP / DNF), trong đó mỗi số hạng tích cơ bản (minterm) tương ứng với một dòng hàm nhận giá trị 1 trong bảng chân trị.',
  },
  {
    id: 'bool_q10',
    topic: 'boolean',
    topicName: 'Khai triển CNF (Tích các tổng / Maxterm)',
    difficulty: 'medium',
    question: 'Dạng nối hội chính tắc (Conjunctive Normal Form - CNF / Product of Maxterms) của một hàm Boole biểu diễn hàm dưới dạng:',
    options: [
      { id: 'A', text: 'Tích của các tổng cơ bản (Maxterms), tương ứng với các dòng hàm nhận giá trị 0' },
      { id: 'B', text: 'Tổng của các tích cơ bản' },
      { id: 'C', text: 'Biểu thức chỉ chứa cổng NOR' },
      { id: 'D', text: 'Phủ định của dạng DNF' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 15-17: Khai triển tích các tổng (POS / CNF) biểu diễn hàm Boole bằng tích của các maxterm tương ứng với các hàng có giá trị hàm bằng 0.',
  },
  {
    id: 'bool_q11',
    topic: 'boolean',
    topicName: 'Cổng NOT (Inverter)',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 19, cổng NOT trong mạch logic có đặc điểm nào sau đây?',
    options: [
      { id: 'A', text: 'Chỉ có 1 đầu vào x, đầu ra F(x) là phủ định của đầu vào (F(x) = ¬x)' },
      { id: 'B', text: 'Có 2 đầu vào, đầu ra là tích của 2 đầu vào' },
      { id: 'C', text: 'Có 2 đầu vào, đầu ra là tổng của 2 đầu vào' },
      { id: 'D', text: 'Không làm thay đổi mức tín hiệu' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 19: Cổng NOT thực hiện hàm phủ định, chỉ có 1 đầu vào x, đầu ra F(x) là phủ định của đầu vào x (¬x).',
  },
  {
    id: 'bool_q12',
    topic: 'boolean',
    topicName: 'Cổng AND',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 20, cổng AND thực hiện hàm logic nào và có đầu ra là gì?',
    options: [
      { id: 'A', text: 'Thực hiện hàm tuyển, đầu ra là x + y' },
      { id: 'B', text: 'Thực hiện hàm hội, đầu ra F(x, y) là tích các đầu vào (F = x * y)' },
      { id: 'C', text: 'Thực hiện hàm phủ định của tổng' },
      { id: 'D', text: 'Thực hiện hàm tương đương' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 20: Cổng AND thực hiện hàm hội, đầu ra F(x, y) là tích (hội) các đầu vào (x * y).',
  },
  {
    id: 'bool_q13',
    topic: 'boolean',
    topicName: 'Cổng OR',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 21, cổng OR thực hiện hàm logic nào và có đầu ra là gì?',
    options: [
      { id: 'A', text: 'Thực hiện hàm hội, đầu ra là x * y' },
      { id: 'B', text: 'Thực hiện hàm phủ định, đầu ra là ¬x' },
      { id: 'C', text: 'Thực hiện hàm tuyển, đầu ra F(x, y) là tổng (tuyển) các đầu vào (F = x + y)' },
      { id: 'D', text: 'Thực hiện hàm so sánh bằng' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 2 trang 21: Cổng OR thực hiện hàm tuyển, đầu ra F(x, y) là tổng (tuyển) các đầu vào (x + y).',
  },
  {
    id: 'bool_q14',
    topic: 'boolean',
    topicName: 'Cổng NAND và NOR',
    difficulty: 'medium',
    question: 'Hai cổng logic cơ sở nào sau đây được gọi là các cổng vạn năng (Universal gates) vì có thể tạo ra mọi hàm Boole?',
    options: [
      { id: 'A', text: 'Cổng AND và Cổng OR' },
      { id: 'B', text: 'Cổng NOT và Cổng Buffer' },
      { id: 'C', text: 'Cổng XOR và Cổng XNOR' },
      { id: 'D', text: 'Cổng NAND (¬(x * y)) và Cổng NOR (¬(x + y))' },
    ],
    correctId: 'D',
    explanation: 'Trong lý thuyết mạch logic số, tập {NAND} hoặc tập {NOR} là hệ đầy đủ (vạn năng) có thể tự thiết kế lại tất cả các cổng NOT, AND, OR cơ bản.',
  },
  {
    id: 'circuit_q01',
    topic: 'boolean',
    topicName: 'Mạch Logic: Cổng NAND vạn năng',
    difficulty: 'hard',
    question: 'Mạch logic gồm 4 cổng NAND vạn năng mắc như hình dưới đây tương đương với hàm logic cơ bản nào giữa hai đầu vào A và B?<br><svg viewBox="0 0 360 145" width="100%" height="auto" style="max-width:360px;display:block;margin:10px auto;background:#0f172a;border:1px solid #334155;border-radius:8px;padding:6px;"><text x="10" y="44" fill="#38bdf8" font-size="13" font-weight="bold">A</text><text x="10" y="100" fill="#f43f5e" font-size="13" font-weight="bold">B</text><path d="M 28 40 L 70 40 L 70 64 L 85 64" fill="none" stroke="#38bdf8" stroke-width="2"/><path d="M 28 96 L 70 96 L 70 78 L 85 78" fill="none" stroke="#f43f5e" stroke-width="2"/><path d="M 85 58 L 105 58 A 14 14 0 0 1 105 84 L 85 84 Z" fill="none" stroke="#e2e8f0" stroke-width="1.8"/><circle cx="122" cy="71" r="2.5" fill="none" stroke="#e2e8f0" stroke-width="1.5"/><text x="94" y="74" fill="#94a3b8" font-size="8" font-weight="bold">NAND1</text><path d="M 50 40 L 50 20 L 150 20" fill="none" stroke="#38bdf8" stroke-width="2"/><path d="M 125 71 L 138 71 L 138 34 L 150 34" fill="none" stroke="#e2e8f0" stroke-width="2"/><path d="M 150 14 L 170 14 A 14 14 0 0 1 170 40 L 150 40 Z" fill="none" stroke="#e2e8f0" stroke-width="1.8"/><circle cx="187" cy="27" r="2.5" fill="none" stroke="#e2e8f0" stroke-width="1.5"/><path d="M 125 71 L 138 71 L 138 108 L 150 108" fill="none" stroke="#e2e8f0" stroke-width="2"/><path d="M 50 96 L 50 122 L 150 122" fill="none" stroke="#f43f5e" stroke-width="2"/><path d="M 150 102 L 170 102 A 14 14 0 0 1 170 128 L 150 128 Z" fill="none" stroke="#e2e8f0" stroke-width="1.8"/><circle cx="187" cy="115" r="2.5" fill="none" stroke="#e2e8f0" stroke-width="1.5"/><path d="M 190 27 L 225 27 L 225 64 L 235 64" fill="none" stroke="#e2e8f0" stroke-width="2"/><path d="M 190 115 L 225 115 L 225 78 L 235 78" fill="none" stroke="#e2e8f0" stroke-width="2"/><path d="M 235 58 L 255 58 A 14 14 0 0 1 255 84 L 235 84 Z" fill="none" stroke="#e2e8f0" stroke-width="1.8"/><circle cx="272" cy="71" r="2.5" fill="none" stroke="#e2e8f0" stroke-width="1.5"/><line x1="275" y1="71" x2="310" y2="71" stroke="#10b981" stroke-width="2.5"/><text x="318" y="75" fill="#10b981" font-size="13" font-weight="bold">Y</text></svg>',
    options: [
      { id: 'A', text: 'Cổng AND (Y = A * B)' },
      { id: 'B', text: 'Cổng OR (Y = A + B)' },
      { id: 'C', text: 'Cổng XOR (Y = A ⊕ B = A*¬B + ¬A*B)' },
      { id: 'D', text: 'Cổng XNOR (Y = ¬(A ⊕ B))' },
    ],
    correctId: 'C',
    explanation: 'Sơ đồ gồm 4 cổng NAND: NAND1 sinh ¬(A*B). NAND2 sinh ¬(A * ¬(A*B)) = ¬A + A*B. NAND3 sinh ¬(B * ¬(A*B)) = ¬B + A*B. NAND4 kết hợp lại cho ngõ ra (A * ¬B) + (¬A * B) = A ⊕ B.',
    actionLink: { view: 'logic', expression: 'p ⊕ q' },
  },
  {
    id: 'bool_q16',
    topic: 'boolean',
    topicName: 'Thiết kế Mạch tổ hợp (Slide trang 22)',
    difficulty: 'medium',
    question: 'Để thiết kế mạch logic tổ hợp có đầu ra là biểu thức xy + ¬xy theo slide Chương 2 trang 22, ta cần tối thiểu bao nhiêu cổng cơ sở nếu chưa tối thiểu hóa?',
    options: [
      { id: 'A', text: '1 cổng NOT, 2 cổng AND và 1 cổng OR' },
      { id: 'B', text: '3 cổng NOT và 1 cổng AND' },
      { id: 'C', text: '2 cổng NOT và 2 cổng OR' },
      { id: 'D', text: '1 cổng NOT và 1 cổng OR' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 22: Biểu thức xy + ¬xy gồm 1 phép phủ định (cổng NOT cho x), 2 phép tích (cổng AND cho xy và ¬xy), và 1 phép tổng (cổng OR kết nối 2 tích).',
  },
  {
    id: 'bool_q17',
    topic: 'boolean',
    topicName: 'Mạch tổ hợp 3 biến (Slide trang 23-24)',
    difficulty: 'medium',
    question: 'Trong slide Chương 2 trang 23-24, hàm Boole f(x, y, z) = xyz + xy¬z + ¬x¬yz được tạo thành từ bao nhiêu số hạng tích (minterm)?',
    options: [
      { id: 'A', text: '2 số hạng' },
      { id: 'B', text: '3 số hạng' },
      { id: 'C', text: '4 số hạng' },
      { id: 'D', text: '8 số hạng' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 23-24: Hàm gồm 3 số hạng tích: xyz, xy¬z và ¬x¬yz. Đầu ra của 3 cổng AND 3 đầu vào được đưa vào 1 cổng OR 3 đầu vào.',
  },
  {
    id: 'bool_q18',
    topic: 'boolean',
    topicName: 'Tối thiểu hóa đại số (Slide trang 26)',
    difficulty: 'medium',
    question: 'Trong slide Chương 2 trang 26, tối thiểu hóa hàm Boole f(x, y, z) = xyz + x¬yz bằng biến đổi đại số ta được biểu thức rút gọn là:',
    options: [
      { id: 'A', text: 'xy' },
      { id: 'B', text: 'yz' },
      { id: 'C', text: 'xz' },
      { id: 'D', text: 'x + z' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 2 trang 26: f(x, y, z) = xyz + x¬yz = xz*(y + ¬y) = xz*1 = xz. Số lượng phép toán giảm đáng kể.',
  },
  {
    id: 'bool_q19',
    topic: 'boolean',
    topicName: 'Tối thiểu hóa đại số (Slide trang 28-30)',
    difficulty: 'medium',
    question: 'Trong slide Chương 2 trang 28-30, tối thiểu hóa hàm Boole f(x, y) = ¬xy + xy + ¬xy bằng phương pháp biến đổi đại số cho kết quả là gì?',
    options: [
      { id: 'A', text: 'y' },
      { id: 'B', text: 'x' },
      { id: 'C', text: 'x + y' },
      { id: 'D', text: 'xy' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 28-30: f(x, y) = ¬xy + xy = (¬x + x)*y = 1*y = y. Mạch tổ hợp tối thiểu chỉ cần 1 đường truyền trực tiếp từ tín hiệu y mà không cần bất kỳ cổng logic nào.',
  },
  {
    id: 'bool_q20',
    topic: 'boolean',
    topicName: 'Bìa Karnaugh 2 biến (Slide trang 31-32)',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 31-32, một bản đồ Karnaugh đối với một hàm Boole 2 biến gồm bao nhiêu ô vuông?',
    options: [
      { id: 'A', text: '2 ô vuông' },
      { id: 'B', text: '4 ô vuông' },
      { id: 'C', text: '8 ô vuông' },
      { id: 'D', text: '16 ô vuông' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 31: Một bản đồ Karnaugh đối với hàm Boole 2 biến gồm bốn ô vuông (2² = 4 ô), tương ứng 4 minterm xy, x¬y, ¬xy, ¬x¬y.',
  },
  {
    id: 'bool_q21',
    topic: 'boolean',
    topicName: 'Bìa Karnaugh 3 biến (Slide trang 35)',
    difficulty: 'easy',
    question: 'Theo slide Chương 2 trang 35, bảng Karnaugh 3 biến là một hình chữ nhật được chia thành bao nhiêu ô?',
    options: [
      { id: 'A', text: '4 ô' },
      { id: 'B', text: '6 ô' },
      { id: 'C', text: '8 ô (2 hàng x 4 cột)' },
      { id: 'D', text: '16 ô' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 2 trang 35: Bảng Karnaugh ba biến là một hình chữ nhật được chia thành 8 ô (2³ = 8 ô), sắp xếp theo lưới 2 hàng x 4 cột.',
  },
  {
    id: 'bool_q22',
    topic: 'boolean',
    topicName: 'Bìa Karnaugh 4 biến',
    difficulty: 'easy',
    question: 'Bảng Karnaugh đối với một hàm Boole 4 biến (w, x, y, z) gồm bao nhiêu ô vuông?',
    options: [
      { id: 'A', text: '8 ô' },
      { id: 'B', text: '12 ô' },
      { id: 'C', text: '32 ô' },
      { id: 'D', text: '16 ô (4 hàng x 4 cột)' },
    ],
    correctId: 'D',
    explanation: 'Bảng Karnaugh 4 biến gồm 2⁴ = 16 ô vuông, biểu diễn dưới dạng ma trận 4x4, các hàng và cột đều đánh số theo mã Gray (00, 01, 11, 10).',
  },
  {
    id: 'bool_q23',
    topic: 'boolean',
    topicName: 'Quy tắc ô kề nhau trên Bìa Karnaugh',
    difficulty: 'medium',
    question: 'Theo slide Chương 2 trang 31, hai ô trong bảng Karnaugh được gọi là "kề nhau" khi thỏa mãn điều kiện gì?',
    options: [
      { id: 'A', text: 'Các hội sơ cấp biểu diễn bởi hai ô đó chỉ khác nhau đúng một biến (một biến xuất hiện ở dạng khẳng định và ở ô kia là phủ định)' },
      { id: 'B', text: 'Hai ô phải cùng nằm trên đường chéo chính' },
      { id: 'C', text: 'Hai ô đều chứa giá trị 0' },
      { id: 'D', text: 'Hai ô có chỉ số minterm cách nhau đúng 2 đơn vị' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 31: Các ô được gọi là kề nhau nếu các hội sơ cấp tương ứng chỉ khác nhau đúng một biến. Việc gộp 2 ô kề nhau cho phép triệt tiêu biến đó theo luật x + ¬x = 1.',
  },
  {
    id: 'bool_q24',
    topic: 'boolean',
    topicName: 'Rút gọn bằng Bìa Karnaugh (Slide trang 33)',
    difficulty: 'medium',
    question: 'Trong slide Chương 2 trang 33, tối thiểu hóa hàm Boole f(x, y) = xy + ¬xy bằng bảng Karnaugh cho kết quả tối thiểu là gì?',
    options: [
      { id: 'A', text: 'x' },
      { id: 'B', text: 'y' },
      { id: 'C', text: 'x + y' },
      { id: 'D', text: '1' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 2 trang 33: Hai ô tương ứng với xy và ¬xy là hai ô kề nhau trên cùng một cột y = 1. Gộp 2 ô này lại triệt tiêu biến x, kết quả tối thiểu là f(x, y) = y.',
  },
  {
    id: 'bool_q25',
    topic: 'boolean',
    topicName: 'Rút gọn bằng Bìa Karnaugh (Slide trang 34)',
    difficulty: 'medium',
    question: 'Trong slide Chương 2 trang 34, hàm Boole f(x, y) = ¬x¬y + ¬xy + xy trên bảng Karnaugh được rút gọn tối thiểu thành dạng nào?',
    options: [
      { id: 'A', text: '¬x + y' },
      { id: 'B', text: 'x + ¬y' },
      { id: 'C', text: '¬x + ¬y' },
      { id: 'D', text: 'x * y' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 2 trang 34: Nhóm 2 ô hàng ¬x (¬x¬y và ¬xy) cho ¬x. Nhóm 2 ô cột y (¬xy và xy) cho y. Hợp hai nhóm lại cho kết quả tối thiểu: f(x, y) = ¬x + y.',
  },
  // =========================================================================
  // CHƯƠNG 3: ĐẠI SỐ TỔ HỢP, ÁNH XẠ & PHƯƠNG PHÁP ĐẾM
  // =========================================================================
  {
    id: 'count_q01',
    topic: 'counting',
    topicName: 'Ánh xạ & Đơn ánh',
    difficulty: 'easy',
    question: 'Một ánh xạ f: A → B được gọi là Đơn ánh (Injective / One-to-one) khi thỏa mãn điều kiện nào?',
    options: [
      { id: 'A', text: 'Mỗi phần tử của B đều có ít nhất một phần tử của A ánh xạ tới' },
      { id: 'B', text: 'Với mọi x₁, x₂ ∈ A, nếu x₁ ≠ x₂ thì f(x₁) ≠ f(x₂)' },
      { id: 'C', text: 'Tập A và tập B có số lượng phần tử bằng nhau' },
      { id: 'D', text: 'Mọi phần tử của A đều ánh xạ tới cùng một phần tử trong B' },
    ],
    correctId: 'B',
    explanation: 'Định nghĩa đơn ánh ở trang 17 slide Chương 3: các phần tử khác nhau ở tập nguồn A phải có ảnh khác nhau ở tập đích B: x₁ ≠ x₂ ⇒ f(x₁) ≠ f(x₂) (tương đương f(x₁) = f(x₂) ⇒ x₁ = x₂).',
    actionLink: { view: 'counting', tab: 'mapping' },
  },
  {
    id: 'count_q02',
    topic: 'counting',
    topicName: 'Toàn ánh & Bản số',
    difficulty: 'medium',
    question: 'Cho hai tập hữu hạn X và Y. Để tồn tại một Toàn ánh (Surjection) từ X lên Y, điều kiện cần về số lượng phần tử là gì?',
    options: [
      { id: 'A', text: '|X| < |Y|' },
      { id: 'B', text: '|X| ≥ |Y|' },
      { id: 'C', text: '|X| + |Y| là số chẵn' },
      { id: 'D', text: '|X| ≤ |Y|' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 18: Toàn ánh đòi hỏi f(X) = Y, tức mỗi phần tử của Y đều có ít nhất 1 tạo ảnh từ X. Do đó tập nguồn phải có số phần tử không ít hơn tập đích (|X| ≥ |Y|).',
    actionLink: { view: 'counting', tab: 'mapping' },
  },
  {
    id: 'count_q03',
    topic: 'counting',
    topicName: 'Song ánh & Ánh xạ ngược',
    difficulty: 'medium',
    question: 'Điều kiện cần và đủ để ánh xạ f: X → Y có ánh xạ ngược f⁻¹: Y → X là gì?',
    options: [
      { id: 'A', text: 'f là đơn ánh' },
      { id: 'B', text: 'f là toàn ánh' },
      { id: 'C', text: 'f là song ánh (vừa đơn ánh vừa toàn ánh)' },
      { id: 'D', text: 'X là tập con của Y' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 3 trang 19: Ánh xạ f có ánh xạ ngược f⁻¹ khi và chỉ khi f là Song ánh. Khi đó mỗi y ∈ Y tương ứng duy nhất với một phần tử x ∈ X.',
    actionLink: { view: 'counting', tab: 'mapping' },
  },
  {
    id: 'count_q04',
    topic: 'counting',
    topicName: 'Tích Descartes của tập hợp',
    difficulty: 'easy',
    question: 'Cho tập A = {a, b} và tập B = {c, d, e}. Số phần tử của tích Descartes A × B là bao nhiêu?',
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '8' },
      { id: 'C', text: '6' },
      { id: 'D', text: '9' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 3 trang 12: Tích Descartes A × B gồm tất cả các cặp có thứ tự (x, y) với x ∈ A và y ∈ B. Số phần tử |A × B| = |A| * |B| = 2 * 3 = 6.',
  },
  {
    id: 'count_q05',
    topic: 'counting',
    topicName: 'Nguyên lý cộng',
    difficulty: 'easy',
    question: 'Một khoa có 15 cán bộ và 135 sinh viên. Theo nguyên lý cộng, có bao nhiêu cách chọn 1 người làm đại diện tham dự đại hội trường?',
    options: [
      { id: 'A', text: '15 + 135 = 150 cách' },
      { id: 'B', text: '15 * 135 = 2025 cách' },
      { id: 'C', text: '135 - 15 = 120 cách' },
      { id: 'D', text: '15! cách' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 21 (Ví dụ nguyên lý cộng): Việc chọn đại diện gồm 2 trường hợp rời nhau: chọn 1 cán bộ (15 cách) hoặc chọn 1 sinh viên (135 cách). Tổng số cách là 15 + 135 = 150.',
  },
  {
    id: 'count_q06',
    topic: 'counting',
    topicName: 'Nguyên lý nhân',
    difficulty: 'medium',
    question: 'Các ghế trong một hội trường được đánh dấu bởi 1 chữ cái tiếng Anh (trong 26 chữ cái) và 1 số nguyên dương không vượt quá 100. Theo nguyên lý nhân, có nhiều nhất bao nhiêu ghế được đánh dấu khác nhau?',
    options: [
      { id: 'A', text: '26 * 100 = 2600 ghế' },
      { id: 'B', text: '26 + 100 = 126 ghế' },
      { id: 'C', text: '100² = 10000 ghế' },
      { id: 'D', text: '26² = 676 ghế' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 24 (Bài tập 2): Một ghế được xác định qua 2 công đoạn liên tiếp: chọn chữ cái (26 cách) và chọn số nguyên từ 1 đến 100 (100 cách). Theo nguyên lý nhân: 26 * 100 = 2600 ghế.',
  },
  {
    id: 'count_q07',
    topic: 'counting',
    topicName: 'Chỉnh hợp không lặp',
    difficulty: 'easy',
    question: 'Có bao nhiêu cách bầu một ban cán sự gồm 1 Lớp trưởng, 1 Lớp phó và 1 Bí thư từ một tập thể gồm 10 sinh viên?',
    options: [
      { id: 'A', text: 'C(10, 3) = 120 cách' },
      { id: 'B', text: 'A(10, 3) = 10 * 9 * 8 = 720 cách' },
      { id: 'C', text: '10³ = 1000 cách' },
      { id: 'D', text: '30 cách' },
    ],
    correctId: 'B',
    explanation: 'Vì 3 chức vụ Lớp trưởng, Lớp phó, Bí thư phân biệt rạch ròi nên việc chọn và sắp đặt có tính thứ tự. Đây là bài toán Chỉnh hợp chập 3 của 10 phần tử: A(10, 3) = 10! / (10 - 3)! = 720 cách.',
    actionLink: { view: 'counting', tab: 'pascal' },
  },
  {
    id: 'count_q08',
    topic: 'counting',
    topicName: 'Hoán vị',
    difficulty: 'easy',
    question: 'Thầy giáo muốn tặng 5 cuốn sách khác nhau cho 5 bạn học sinh, mỗi bạn nhận đúng 1 cuốn. Hỏi có bao nhiêu cách tặng sách?',
    options: [
      { id: 'A', text: 'P₅ = 5! = 120 cách' },
      { id: 'B', text: '5⁵ = 3125 cách' },
      { id: 'C', text: 'C(5, 1) = 5 cách' },
      { id: 'D', text: '25 cách' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 26: Số cách xếp 5 cuốn sách phân biệt cho 5 học sinh là số hoán vị của 5 phần tử: P₅ = 5! = 5 * 4 * 3 * 2 * 1 = 120 cách.',
  },
  {
    id: 'count_q09',
    topic: 'counting',
    topicName: 'Tổ hợp',
    difficulty: 'medium',
    question: 'Một tổ gồm 8 nam và 6 nữ. Có bao nhiêu cách chọn một nhóm gồm 5 người sao cho trong đó có đúng 2 nữ?',
    options: [
      { id: 'A', text: 'C(14, 5) = 2002 cách' },
      { id: 'B', text: 'C(6, 2) * C(8, 3) = 15 * 56 = 840 cách' },
      { id: 'C', text: 'A(6, 2) * A(8, 3) = 10080 cách' },
      { id: 'D', text: 'C(6, 2) + C(8, 3) = 71 cách' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 27: Nhóm 5 người có đúng 2 nữ đồng nghĩa với việc có 3 nam. Số cách chọn 2 nữ từ 6 nữ là C(6, 2) = 15. Số cách chọn 3 nam từ 8 nam là C(8, 3) = 56. Theo quy tắc nhân: 15 * 56 = 840 cách.',
    actionLink: { view: 'counting', tab: 'pascal' },
  },
  {
    id: 'count_q10',
    topic: 'counting',
    topicName: 'Chỉnh hợp lặp',
    difficulty: 'easy',
    question: 'Để đăng ký ký hiệu một loại máy mới, người ta dùng chuỗi gồm 3 chữ số lấy từ 9 chữ số {1, 2, 3, ..., 9} (các chữ số được phép lặp lại). Có thể tạo được bao nhiêu ký hiệu máy khác nhau?',
    options: [
      { id: 'A', text: '9³ = 729 ký hiệu' },
      { id: 'B', text: 'A(9, 3) = 504 ký hiệu' },
      { id: 'C', text: 'C(9, 3) = 84 ký hiệu' },
      { id: 'D', text: '9 * 3 = 27 ký hiệu' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 30: Đây là chỉnh hợp lặp chập 3 của 9 phần tử. Mỗi vị trí có 9 cách chọn độc lập, tổng cộng 9 * 9 * 9 = 9³ = 729 ký hiệu.',
  },
  {
    id: 'count_q11',
    topic: 'counting',
    topicName: 'Tổ hợp lặp',
    difficulty: 'medium',
    question: 'Có 4 loại bút bi (xanh, đỏ, vàng, tím), mỗi loại có sẵn số lượng lớn. Có bao nhiêu cách chọn ra 6 cây bút bất kỳ?',
    options: [
      { id: 'A', text: '4⁶ = 4096 cách' },
      { id: 'B', text: 'K(4, 6) = C(4+6-1, 6) = C(9, 6) = 84 cách' },
      { id: 'C', text: 'C(6, 4) = 15 cách' },
      { id: 'D', text: 'A(9, 6) = 60480 cách' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 29 (Ví dụ tổ hợp lặp): Chọn 6 cây bút từ 4 loại là tổ hợp lặp chập 6 của 4 phần tử: K(n, k) = C(n+k-1, k) = C(4+6-1, 6) = C(9, 6) = 84 cách.',
    actionLink: { view: 'counting', tab: 'pascal' },
  },
  {
    id: 'count_q12',
    topic: 'counting',
    topicName: 'Hệ thức truy hồi Tháp Hà Nội',
    difficulty: 'easy',
    question: 'Bài toán Tháp Hà Nội với n đĩa có hệ thức truy hồi H_n = 2*H_{n-1} + 1 với H₁ = 1. Số bước chuyển tối thiểu để dời toàn bộ tháp có n = 4 đĩa là bao nhiêu?',
    options: [
      { id: 'A', text: '7 bước' },
      { id: 'B', text: '8 bước' },
      { id: 'C', text: '15 bước (2⁴ - 1)' },
      { id: 'D', text: '16 bước (2⁴)' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 3 trang 43: Nghiệm tường minh của hệ thức Tháp Hà Nội là H_n = 2ⁿ - 1. Với n = 4 đĩa: H₄ = 2⁴ - 1 = 16 - 1 = 15 bước.',
    actionLink: { view: 'counting', tab: 'recurrence' },
  },
  {
    id: 'count_q13',
    topic: 'counting',
    topicName: 'Nguyên lý Dirichlet (Chuồng bồ câu)',
    difficulty: 'easy',
    question: 'Theo Nguyên lý Dirichlet, trong một nhóm gồm 367 người, khẳng định nào sau đây chắc chắn đúng?',
    options: [
      { id: 'A', text: 'Mọi người đều có ngày sinh khác nhau' },
      { id: 'B', text: 'Có ít nhất 2 người có cùng ngày sinh nhật trong năm (kể cả năm nhuận 366 ngày)' },
      { id: 'C', text: 'Có đúng 2 người sinh cùng ngày' },
      { id: 'D', text: 'Có ít nhất 3 người sinh cùng ngày' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 31: Một năm có tối đa 366 ngày (chuồng). Có 367 người (bồ câu). Theo nguyên lý Dirichlet, vì 367 > 366 nên chắc chắn có ít nhất ⌈367/366⌉ = 2 người có cùng ngày sinh.',
    actionLink: { view: 'counting', tab: 'dirichlet' },
  },
  {
    id: 'count_q14',
    topic: 'counting',
    topicName: 'Nguyên lý Dirichlet mở rộng',
    difficulty: 'medium',
    question: 'Cần chọn ít nhất bao nhiêu sinh viên để chắc chắn có ít nhất 3 sinh viên sinh cùng một tháng trong năm?',
    options: [
      { id: 'A', text: '2 * 12 + 1 = 25 sinh viên' },
      { id: 'B', text: '3 * 12 = 36 sinh viên' },
      { id: 'C', text: '13 sinh viên' },
      { id: 'D', text: '24 sinh viên' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 32: Có k = 12 tháng. Theo nguyên tắc xấu nhất, mỗi tháng có tối đa 2 người (2 * 12 = 24 người). Do đó chỉ cần thêm 1 người nữa (24 + 1 = 25 sinh viên) thì theo nguyên lý Dirichlet chắc chắn có ít nhất ⌈25/12⌉ = 3 sinh viên cùng tháng sinh.',
    actionLink: { view: 'counting', tab: 'dirichlet' },
  },
  {
    id: 'count_q15',
    topic: 'counting',
    topicName: 'Nguyên lý bù trừ',
    difficulty: 'medium',
    question: 'Theo nguyên lý bù trừ, nếu lớp CNTT có 150 sinh viên học môn Java, 160 sinh viên học môn Thiết kế Web, và 40 sinh viên học cả hai môn, thì tổng số sinh viên học ít nhất một trong hai môn là bao nhiêu?',
    options: [
      { id: 'A', text: '150 + 160 - 40 = 270 sinh viên' },
      { id: 'B', text: '150 + 160 + 40 = 350 sinh viên' },
      { id: 'C', text: '150 + 160 = 310 sinh viên' },
      { id: 'D', text: '230 sinh viên' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 23: Nguyên lý bù trừ cho hai tập hợp: |A ∪ B| = |A| + |B| - |A ∩ B| = 150 + 160 - 40 = 270 sinh viên.',
  },
  {
    id: 'count_q16',
    topic: 'counting',
    topicName: 'Hệ thức truy hồi bậc 1',
    difficulty: 'easy',
    question: 'Giải hệ thức truy hồi thuần nhất bậc 1: a_n = 3*a_{n-1} với điều kiện đầu a_0 = 2. Nghiệm tổng quát của hệ thức là gì?',
    options: [
      { id: 'A', text: 'a_n = 2 + 3n' },
      { id: 'B', text: 'a_n = 2 * 3ⁿ' },
      { id: 'C', text: 'a_n = 3 * 2ⁿ' },
      { id: 'D', text: 'a_n = 3ⁿ' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 42: Bằng phương pháp lặp lùi: a_n = 3*a_{n-1} = 3²*a_{n-2} = ... = 3ⁿ*a₀ = 2 * 3ⁿ.',
    actionLink: { view: 'counting', tab: 'recurrence' },
  },
  {
    id: 'count_q17',
    topic: 'counting',
    topicName: 'Phương trình đặc trưng bậc 2',
    difficulty: 'medium',
    question: 'Phương trình đặc trưng của hệ thức truy hồi tuyến tính thuần nhất S(n) = 5*S(n-1) - 6*S(n-2) là phương trình nào?',
    options: [
      { id: 'A', text: 'r² + 5r - 6 = 0' },
      { id: 'B', text: 'r² - 5r + 6 = 0' },
      { id: 'C', text: 'r² - 6r + 5 = 0' },
      { id: 'D', text: 'r² + 6r + 5 = 0' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 45: Đưa về dạng chuẩn S(n) - 5*S(n-1) + 6*S(n-2) = 0. Phương trình đặc trưng tương ứng là r² - 5r + 6 = 0.',
    actionLink: { view: 'counting', tab: 'recurrence' },
  },
  {
    id: 'count_q18',
    topic: 'counting',
    topicName: 'Nghiệm tổng quát bậc 2',
    difficulty: 'medium',
    question: 'Nghiệm tổng quát của hệ thức truy hồi S(n) = 5*S(n-1) - 6*S(n-2) có dạng nào sau đây (với α₁, α₂ là các hằng số)?',
    options: [
      { id: 'A', text: 'S(n) = α₁ * 2ⁿ + α₂ * 3ⁿ' },
      { id: 'B', text: 'S(n) = α₁ * 5ⁿ + α₂ * 6ⁿ' },
      { id: 'C', text: 'S(n) = (α₁ + α₂*n) * 2ⁿ' },
      { id: 'D', text: 'S(n) = α₁ * 2ⁿ - α₂ * 3ⁿ' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 45-46: Phương trình đặc trưng r² - 5r + 6 = 0 có 2 nghiệm phân biệt r₁ = 2, r₂ = 3. Nghiệm tổng quát có dạng S(n) = α₁ * 2ⁿ + α₂ * 3ⁿ.',
    actionLink: { view: 'counting', tab: 'recurrence' },
  },
  {
    id: 'count_q19',
    topic: 'counting',
    topicName: 'Nghiệm kép phương trình đặc trưng',
    difficulty: 'hard',
    question: 'Hệ thức truy hồi S(n) = 4*S(n-1) - 4*S(n-2) có phương trình đặc trưng r² - 4r + 4 = 0 nghiệm kép r₀ = 2. Nghiệm tổng quát của hệ thức có dạng là gì?',
    options: [
      { id: 'A', text: 'S(n) = (α₁ + α₂*n) * 2ⁿ' },
      { id: 'B', text: 'S(n) = α₁ * 2ⁿ + α₂ * 4ⁿ' },
      { id: 'C', text: 'S(n) = α₁ * 2ⁿ' },
      { id: 'D', text: 'S(n) = α₁ * 4ⁿ + α₂*n' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 47: Khi phương trình đặc trưng có nghiệm kép r₀, nghiệm tổng quát của hệ thức truy hồi có dạng S(n) = (α₁ + α₂*n) * r₀ⁿ = (α₁ + α₂*n) * 2ⁿ.',
    actionLink: { view: 'counting', tab: 'recurrence' },
  },
  {
    id: 'count_q20',
    topic: 'counting',
    topicName: 'Số chuỗi bit nhị phân',
    difficulty: 'easy',
    question: 'Số xâu nhị phân (bit string) có độ dài n là bao nhiêu?',
    options: [
      { id: 'A', text: '2ⁿ' },
      { id: 'B', text: '2n' },
      { id: 'C', text: 'n²' },
      { id: 'D', text: 'n!' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 30: Mỗi vị trí trong xâu nhị phân có 2 khả năng (0 hoặc 1). Với độ dài n, số xâu nhị phân là 2 * 2 * ... * 2 = 2ⁿ.',
  },
  {
    id: 'count_q21',
    topic: 'counting',
    topicName: 'Chỉnh hợp phân biệt tiết học',
    difficulty: 'medium',
    question: 'Một lớp phải học 10 môn, mỗi ngày xếp học 2 môn phân biệt theo thứ tự (tiết 1, tiết 2). Hỏi có bao nhiêu cách sắp xếp thời khóa biểu trong 1 ngày?',
    options: [
      { id: 'A', text: 'C(10, 2) = 45 cách' },
      { id: 'B', text: 'A(10, 2) = 90 cách' },
      { id: 'C', text: '10² = 100 cách' },
      { id: 'D', text: '20 cách' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 28 (Ví dụ thời khóa biểu): Chọn 2 môn từ 10 môn có phân biệt thứ tự tiết học là chỉnh hợp chập 2 của 10: A(10, 2) = 10 * 9 = 90 cách.',
  },
  {
    id: 'count_q22',
    topic: 'counting',
    topicName: 'Số lượng song ánh',
    difficulty: 'easy',
    question: 'Số song ánh khác nhau từ một tập X có n phần tử vào chính nó bằng bao nhiêu?',
    options: [
      { id: 'A', text: '2ⁿ' },
      { id: 'B', text: 'n!' },
      { id: 'C', text: 'nⁿ' },
      { id: 'D', text: 'C(n, 2)' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 19: Mỗi song ánh từ tập n phần tử vào chính nó tương ứng với một hoán vị của n phần tử. Do đó có đúng n! song ánh.',
  },
  {
    id: 'count_q23',
    topic: 'counting',
    topicName: 'Bài toán đếm số chia hết cho 2',
    difficulty: 'medium',
    question: 'Cho tập X = {1, 2, 3, 4, 5, 0}. Có bao nhiêu số tự nhiên gồm 3 chữ số đôi một khác nhau và chia hết cho 2?',
    options: [
      { id: 'A', text: '60 số' },
      { id: 'B', text: '52 số' },
      { id: 'C', text: '48 số' },
      { id: 'D', text: '100 số' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 3 trang 24 (Bài tập 1): Số có dạng abc chia hết cho 2. TH1: c = 0 có 5 * 4 = 20 số. TH2: c ∈ {2, 4} có 2 cách chọn c; chữ số a ≠ 0 và a ≠ c có 4 cách; chữ số b có 4 cách ⇒ 2 * 4 * 4 = 32 số. Tổng cộng: 20 + 32 = 52 số.',
  },
  {
    id: 'count_q24',
    topic: 'counting',
    topicName: 'Hệ thức tam giác Pascal',
    difficulty: 'easy',
    question: 'Đẳng thức tổ hợp kinh điển nào sau đây đúng (hệ thức Pascal)?',
    options: [
      { id: 'A', text: 'C(n, k) = C(n-1, k-1) + C(n-1, k)' },
      { id: 'B', text: 'C(n, k) = C(n-1, k-1) * C(n-1, k)' },
      { id: 'C', text: 'C(n, k) = C(n, k-1) + C(n, k+1)' },
      { id: 'D', text: 'C(n, k) = C(n-1, k) - C(n-1, k-1)' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 3 trang 27: Tính chất cơ bản của tổ hợp: C(n, k) = C(n-1, k-1) + C(n-1, k) (công thức xây dựng tam giác Pascal).',
    actionLink: { view: 'counting', tab: 'pascal' },
  },
  {
    id: 'count_q25',
    topic: 'counting',
    topicName: 'Hoán vị có phần tử cố định',
    difficulty: 'medium',
    question: 'Có bao nhiêu cách xếp 5 bạn A, B, C, D, E vào một hàng ngang gồm 5 ghế sao cho bạn C luôn ngồi chính giữa?',
    options: [
      { id: 'A', text: '5! = 120 cách' },
      { id: 'B', text: '3! = 6 cách' },
      { id: 'C', text: '4! = 24 cách' },
      { id: 'D', text: '12 cách' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 3 trang 25 (Bài tập 6): Bạn C cố định ở vị trí giữa ghế (ghế số 3). Xếp 4 bạn còn lại vào 4 chiếc ghế còn lại có P₄ = 4! = 24 cách.',
  },

  // =========================================================================
  // CHƯƠNG 4: QUAN HỆ HAI NGÔI, TƯƠNG ĐƯƠNG & QUAN HỆ THỨ TỰ (POSET)
  // =========================================================================
  {
    id: 'rel_q01',
    topic: 'relation',
    topicName: 'Ma trận Boolean của quan hệ',
    difficulty: 'easy',
    question: 'Cho quan hệ R trên tập A = {1, 2, 3} xác định bởi R = {(1, 1), (1, 2), (2, 3), (3, 3)}. Phần tử ở hàng 1 cột 3 của ma trận Boolean M_R[1, 3] có giá trị là bao nhiêu?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '0' },
      { id: 'C', text: '3' },
      { id: 'D', text: 'Không xác định' },
    ],
    correctId: 'B',
    explanation: 'Theo định nghĩa ma trận biểu diễn quan hệ Boolean: M_R[i, j] = 1 nếu (aᵢ, aⱼ) ∈ R, và bằng 0 nếu ngược lại. Vì cặp (1, 3) ∉ R nên M_R[1, 3] = 0.',
    actionLink: { view: 'relation', tab: 'matrix' },
  },
  {
    id: 'rel_q02',
    topic: 'relation',
    topicName: 'Tính chất Phản xạ',
    difficulty: 'easy',
    question: 'Quan hệ hai ngôi R trên tập A được gọi là Phản xạ (Reflexive) khi và chỉ khi thỏa mãn điều kiện nào?',
    options: [
      { id: 'A', text: 'Với mọi a, b ∈ A, nếu a R b thì b R a' },
      { id: 'B', text: 'Với mọi a ∈ A, luôn có a R a' },
      { id: 'C', text: 'Với mọi a, b ∈ A, nếu a R b và b R a thì a = b' },
      { id: 'D', text: 'Tồn tại ít nhất một phần tử a sao cho a R a' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 6: Định nghĩa quan hệ phản xạ: ∀a ∈ A, a R a (mọi phần tử đều có quan hệ với chính nó).',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q03',
    topic: 'relation',
    topicName: 'Dấu hiệu Ma trận Phản xạ',
    difficulty: 'easy',
    question: 'Dấu hiệu nhận biết nhanh nhất một quan hệ R trên tập A có tính chất phản xạ (Reflexive) thông qua ma trận Boolean M_R là gì?',
    options: [
      { id: 'A', text: 'Tất cả các phần tử trên đường chéo chính đều bằng 1 (M_R[i, i] = 1, ∀i)' },
      { id: 'B', text: 'Tất cả các phần tử ngoài đường chéo chính đều bằng 0' },
      { id: 'C', text: 'Ma trận đối xứng qua đường chéo chính' },
      { id: 'D', text: 'Đường chéo chính chứa ít nhất một số 1' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 7: Tính phản xạ đòi hỏi (a, a) ∈ R với mọi a ∈ A. Do đó, tất cả các ô trên đường chéo chính M_R[i, i] đều bắt buộc phải mang giá trị 1.',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q04',
    topic: 'relation',
    topicName: 'Tính chất Đối xứng',
    difficulty: 'easy',
    question: 'Quan hệ R trên tập A được gọi là Đối xứng (Symmetric) khi và chỉ khi thỏa mãn điều kiện nào?',
    options: [
      { id: 'A', text: 'Với mọi a, b ∈ A, nếu a R b thì b R a' },
      { id: 'B', text: 'Với mọi a, b ∈ A, nếu a R b và b R a thì a = b' },
      { id: 'C', text: 'Với mọi a ∈ A, a R a' },
      { id: 'D', text: 'Với mọi a, b, c ∈ A, nếu a R b và b R c thì a R c' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 8: Định nghĩa quan hệ đối xứng: ∀a, b ∈ A, (a R b) → (b R a).',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q05',
    topic: 'relation',
    topicName: 'Tính chất Phản đối xứng',
    difficulty: 'easy',
    question: 'Quan hệ R trên tập A được gọi là Phản đối xứng (Antisymmetric) khi thỏa mãn điều kiện nào?',
    options: [
      { id: 'A', text: 'Với mọi a, b ∈ A, nếu a R b thì b không có quan hệ với a' },
      { id: 'B', text: 'Với mọi a, b ∈ A, nếu (a R b) và (b R a) thì bắt buộc a = b' },
      { id: 'C', text: 'Không có phần tử nào có quan hệ với chính nó' },
      { id: 'D', text: 'Ma trận M_R có đường chéo toàn số 0' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 8: Định nghĩa quan hệ phản đối xứng: ∀a, b ∈ A, (a R b) * (b R a) → (a = b). Nghĩa là với 2 phần tử phân biệt a ≠ b, không thể đồng thời có cả a R b và b R a.',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q06',
    topic: 'relation',
    topicName: 'Tính chất Bắc cầu',
    difficulty: 'easy',
    question: 'Quan hệ R trên tập A được gọi là Bắc cầu (Transitive / Truyền) khi thỏa mãn điều kiện nào?',
    options: [
      { id: 'A', text: 'Với mọi a, b ∈ A, nếu a R b thì b R a' },
      { id: 'B', text: 'Với mọi a ∈ A, a R a' },
      { id: 'C', text: 'Với mọi a, b, c ∈ A, nếu (a R b) và (b R c) thì (a R c)' },
      { id: 'D', text: 'Ma trận M_R bằng chuyển vị của chính nó' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 4 trang 11: Định nghĩa tính bắc cầu: ∀a, b, c ∈ A, (a R b) * (b R c) → (a R c).',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q07',
    topic: 'relation',
    topicName: 'Quan hệ tương đương',
    difficulty: 'easy',
    question: 'Một quan hệ R trên tập A được gọi là Quan hệ tương đương (Equivalence relation) khi thỏa mãn đồng thời 3 tính chất nào?',
    options: [
      { id: 'A', text: 'Phản xạ, Phản đối xứng, Bắc cầu' },
      { id: 'B', text: 'Đối xứng, Phản đối xứng, Bắc cầu' },
      { id: 'C', text: 'Phản xạ, Đối xứng, Bắc cầu' },
      { id: 'D', text: 'Phản xạ, Đối xứng, Toàn phần' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 4 trang 15: Định nghĩa quan hệ tương đương: thỏa mãn 3 tính chất: Phản xạ, Đối xứng và Bắc cầu.',
    actionLink: { view: 'relation', tab: 'equivalence' },
  },
  {
    id: 'rel_q08',
    topic: 'relation',
    topicName: 'Quan hệ thứ tự (POSET)',
    difficulty: 'easy',
    question: 'Một quan hệ R trên tập A được gọi là Quan hệ thứ tự (POSET) khi thỏa mãn đồng thời 3 tính chất nào?',
    options: [
      { id: 'A', text: 'Phản xạ, Phản đối xứng, Bắc cầu' },
      { id: 'B', text: 'Phản xạ, Đối xứng, Bắc cầu' },
      { id: 'C', text: 'Đối xứng, Phản đối xứng, Bắc cầu' },
      { id: 'D', text: 'Phản xạ, Bắc cầu, Liên thông' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 24: Định nghĩa quan hệ thứ tự: thỏa mãn 3 tính chất: Phản xạ, Phản đối xứng và Bắc cầu. Ký hiệu cặp (A, ≤) là POSET.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q09',
    topic: 'relation',
    topicName: 'Đồng dư Modulo m',
    difficulty: 'medium',
    question: 'Cho số nguyên dương m. Quan hệ đồng dư modulo m trên tập số nguyên ℤ (a ≡ b (mod m) ⇔ m | (a - b)) là loại quan hệ nào?',
    options: [
      { id: 'A', text: 'Quan hệ thứ tự toàn phần' },
      { id: 'B', text: 'Quan hệ tương đương' },
      { id: 'C', text: 'Quan hệ phản xạ nhưng không đối xứng' },
      { id: 'D', text: 'Quan hệ không bắc cầu' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 16: Quan hệ đồng dư modulo m có tính phản xạ (m | 0), đối xứng (m | (a-b) ⇔ m | (b-a)), và bắc cầu (m | (a-b) và m | (b-c) ⇒ m | (a-c)). Do đó đây là một Quan hệ tương đương.',
    actionLink: { view: 'relation', tab: 'equivalence' },
  },
  {
    id: 'rel_q10',
    topic: 'relation',
    topicName: 'Phân hoạch lớp đồng dư ℤ_m',
    difficulty: 'easy',
    question: 'Tập hợp các số nguyên ℤ theo quan hệ đồng dư modulo m được phân hoạch thành bao nhiêu lớp tương đương rời nhau?',
    options: [
      { id: 'A', text: 'Vô số lớp' },
      { id: 'B', text: 'Đúng m lớp: [0], [1], ..., [m-1]' },
      { id: 'C', text: 'm - 1 lớp' },
      { id: 'D', text: '2ᵐ lớp' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 21: Có đúng m lớp đồng dư modulo m là [0]ₘ, [1]ₘ, ..., [m-1]ₘ. Chúng lập thành một phân hoạch của ℤ thành các tập con rời nhau.',
    actionLink: { view: 'relation', tab: 'equivalence' },
  },
  {
    id: 'rel_q11',
    topic: 'relation',
    topicName: 'Kiểm tra tính phản xạ',
    difficulty: 'medium',
    question: 'Cho tập A = {1, 2, 3, 4} và quan hệ R = {(1, 1), (1, 2), (2, 1), (2, 2), (3, 4), (4, 1), (4, 4)}. Quan hệ R không có tính phản xạ vì sao?',
    options: [
      { id: 'A', text: 'Vì (3, 3) ∉ R' },
      { id: 'B', text: 'Vì (1, 2) ∈ R' },
      { id: 'C', text: 'Vì (4, 1) ∈ R' },
      { id: 'D', text: 'Vì đường chéo chính chứa số 1' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 6 (Ví dụ R1): Trên tập A = {1, 2, 3, 4}, quan hệ R thiếu phần tử (3, 3) nên không thỏa mãn điều kiện phản xạ (mọi a ∈ A đều phải có a R a).',
    actionLink: { view: 'relation', tab: 'properties' },
  },
  {
    id: 'rel_q12',
    topic: 'relation',
    topicName: 'Phản ví dụ POSET trên ℤ',
    difficulty: 'medium',
    question: 'Quan hệ ước số "a | b" trên tập số nguyên dương ℤ⁺ là một POSET. Tuy nhiên quan hệ ước số trên tập số nguyên ℤ (chứa cả số âm) KHÔNG phải là một POSET vì vi phạm tính chất nào?',
    options: [
      { id: 'A', text: 'Tính phản xạ' },
      { id: 'B', text: 'Tính phản đối xứng (vì 3 | -3 và -3 | 3 nhưng 3 ≠ -3)' },
      { id: 'C', text: 'Tính bắc cầu' },
      { id: 'D', text: 'Không vi phạm tính chất nào' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 26: Trên ℤ, ta có 3 | -3 và -3 | 3 nhưng 3 ≠ -3. Do đó vi phạm tính phản đối xứng, nên (ℤ, |) không phải là một POSET.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q13',
    topic: 'relation',
    topicName: 'Biểu đồ Hasse: Quy ước vẽ',
    difficulty: 'medium',
    question: 'Trong biểu đồ Hasse của một tập sắp thứ tự (POSET), các cung có đặc điểm gì theo quy ước chuẩn trong giáo trình?',
    options: [
      { id: 'A', text: 'Vẽ mũi tên chỉ từ trên xuống dưới' },
      { id: 'B', text: 'Không vẽ mũi tên, các cung ngầm hiểu đi từ dưới lên trên và đã loại bỏ khuyên cùng cạnh bắc cầu' },
      { id: 'C', text: 'Vẽ tất cả các khuyên tại mỗi đỉnh' },
      { id: 'D', text: 'Vẽ mũi tên hai chiều' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 32: Biểu đồ Hasse tối giản bằng cách bỏ tất cả khuyên (tính phản xạ), bỏ các cạnh bắc cầu, và quy ước mọi cung đều đi từ dưới lên trên nên không cần vẽ mũi tên.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q14',
    topic: 'relation',
    topicName: 'Phần tử tối đại (Maximal)',
    difficulty: 'medium',
    question: 'Trong một POSET hữu hạn (S, ≤), phần tử tối đại (Maximal element) m được định nghĩa là phần tử:',
    options: [
      { id: 'A', text: 'Không có phần tử nào trong S lớn hơn m (không có cung xuất phát đi lên từ m)' },
      { id: 'B', text: 'Lớn hơn mọi phần tử khác trong S' },
      { id: 'C', text: 'Nhỏ hơn mọi phần tử khác trong S' },
      { id: 'D', text: 'Luôn luôn là duy nhất' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 34: Phần tử tối đại là phần tử không bị trội bởi phần tử nào khác trong S (không có cung nào xuất phát đi lên từ điểm tối đại). Phần tử tối đại có thể có nhiều và không nhất thiết so sánh được với mọi phần tử.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q15',
    topic: 'relation',
    topicName: 'Tìm phần tử tối đại POSET',
    difficulty: 'medium',
    question: 'Cho POSET S = ({2, 4, 5, 10, 12, 20, 25}, | ) với quan hệ chia hết. Các phần tử tối đại của S là gì?',
    options: [
      { id: 'A', text: '{2, 5}' },
      { id: 'B', text: '{12, 20, 25}' },
      { id: 'C', text: '{25}' },
      { id: 'D', text: '{20}' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 36 (Ví dụ phần tử tối đại): Các số 12, 20, 25 không chia hết cho số nào khác lớn hơn chúng trong tập S. Do đó {12, 20, 25} là các phần tử tối đại.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q16',
    topic: 'relation',
    topicName: 'Tìm phần tử tối tiểu POSET',
    difficulty: 'medium',
    question: 'Cho POSET S = ({2, 4, 5, 10, 12, 20, 25}, | ) với quan hệ chia hết. Các phần tử tối tiểu của S là gì?',
    options: [
      { id: 'A', text: '{2, 5}' },
      { id: 'B', text: '{12, 20, 25}' },
      { id: 'C', text: '{2}' },
      { id: 'D', text: '{4, 10}' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 36: Các số 2 và 5 không có ước số nào khác nhỏ hơn chúng trong tập S (không có cung kết thúc ở chúng). Do đó {2, 5} là các phần tử tối tiểu.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q17',
    topic: 'relation',
    topicName: 'Tính duy nhất của phần tử lớn nhất',
    difficulty: 'easy',
    question: 'Phần tử lớn nhất (Greatest element) của một POSET (nếu tồn tại) có tính chất gì đặc biệt?',
    options: [
      { id: 'A', text: 'Luôn luôn có ít nhất 2 phần tử' },
      { id: 'B', text: 'Không thể so sánh được với các phần tử khác' },
      { id: 'C', text: 'Luôn luôn trùng với phần tử tối tiểu' },
      { id: 'D', text: 'Nếu tồn tại thì phần tử lớn nhất là duy nhất' },
    ],
    correctId: 'D',
    explanation: 'Slide Chương 4 trang 36: Phần tử lớn nhất lớn hơn mọi phần tử khác trong POSET. Nếu tồn tại, phần tử lớn nhất luôn luôn là DUY NHẤT (khác với phần tử tối đại có thể có nhiều).',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q18',
    topic: 'relation',
    topicName: 'POSET tập lũy thừa P(S)',
    difficulty: 'medium',
    question: 'Quan hệ bao hàm tập con (P(S), ⊆) trên tập các tập con của S có phải là một POSET không?',
    options: [
      { id: 'A', text: 'Có, vì quan hệ ⊆ có tính phản xạ, phản đối xứng và bắc cầu' },
      { id: 'B', text: 'Không, vì không có tính phản xạ' },
      { id: 'C', text: 'Không, vì không có tính bắc cầu' },
      { id: 'D', text: 'Không, vì vi phạm tính phản đối xứng' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 27: Với mọi tập A, B, C: A ⊆ A (phản xạ); A ⊆ B và B ⊆ A ⇒ A = B (phản đối xứng); A ⊆ B và B ⊆ C ⇒ A ⊆ C (bắc cầu). Do đó (P(S), ⊆) là một POSET.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'relation_q19',
    topic: 'relation',
    topicName: 'Thứ tự toàn phần',
    difficulty: 'medium',
    question: 'Quan hệ thứ tự nào sau đây là Thứ tự toàn phần (Linear / Total order)?',
    options: [
      { id: 'A', text: 'Quan hệ ước số "a | b" trên tập số nguyên dương ℤ⁺' },
      { id: 'B', text: 'Quan hệ "≤" trên tập số nguyên dương ℤ⁺' },
      { id: 'C', text: 'Quan hệ tập con "⊆" trên P({1, 2})' },
      { id: 'D', text: 'Quan hệ đồng dư mod 3' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 28-29: Thứ tự toàn phần là POSET mà hai phần tử bất kỳ luôn so sánh được với nhau. Trên ℤ⁺, với hai số bất kỳ luôn có a ≤ b hoặc b ≤ a. Trong khi với quan hệ ước số thì 5 và 7 không so sánh được.',
    actionLink: { view: 'relation', tab: 'poset' },
  },
  {
    id: 'rel_q20',
    topic: 'relation',
    topicName: 'Bao đóng phản xạ',
    difficulty: 'easy',
    question: 'Bao đóng phản xạ (Reflexive closure) r(R) của quan hệ R trên tập A được xác định bằng công thức nào?',
    options: [
      { id: 'A', text: 'r(R) = R ∪ Δ_A (với Δ_A = {(a, a) | a ∈ A})' },
      { id: 'B', text: 'r(R) = R ∩ Δ_A' },
      { id: 'C', text: 'r(R) = R ∪ R⁻¹' },
      { id: 'D', text: 'r(R) = R \\ Δ_A' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 7: Bao đóng phản xạ là quan hệ phản xạ nhỏ nhất chứa R, thu được bằng cách bổ sung toàn bộ đường chéo Δ_A: r(R) = R ∪ Δ_A (ma trận M_{r(R)} = M_R + Iₙ).',
    actionLink: { view: 'relation', tab: 'closure' },
  },
  {
    id: 'rel_q21',
    topic: 'relation',
    topicName: 'Bao đóng đối xứng',
    difficulty: 'easy',
    question: 'Bao đóng đối xứng (Symmetric closure) s(R) của quan hệ R trên tập A được xác định bằng công thức nào?',
    options: [
      { id: 'A', text: 's(R) = R ∩ R⁻¹' },
      { id: 'B', text: 's(R) = R ∪ R⁻¹ (với R⁻¹ = {(b, a) | (a, b) ∈ R})' },
      { id: 'C', text: 's(R) = R ∪ Δ_A' },
      { id: 'D', text: 's(R) = R \\ R⁻¹' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 8: Bao đóng đối xứng thu được bằng cách thêm các cặp nghịch đảo (b, a) nếu (a, b) ∈ R: s(R) = R ∪ R⁻¹ (ma trận M_{s(R)} = M_R + M_Rᵀ).',
    actionLink: { view: 'relation', tab: 'closure' },
  },
  {
    id: 'rel_q22',
    topic: 'relation',
    topicName: 'Thuật toán Warshall',
    difficulty: 'medium',
    question: 'Thuật toán Warshall được sử dụng để tìm bao đóng nào của quan hệ hai ngôi hữu hạn?',
    options: [
      { id: 'A', text: 'Bao đóng bắc cầu (Transitive closure)' },
      { id: 'B', text: 'Bao đóng phản xạ' },
      { id: 'C', text: 'Bao đóng đối xứng' },
      { id: 'D', text: 'Bao đóng tương đương' },
    ],
    correctId: 'A',
    explanation: 'Thuật toán Warshall tính ma trận đường đi / bao đóng bắc cầu t(R) qua n bước lặp trung gian: W_k[i, j] = W_{k-1}[i, j] + (W_{k-1}[i, k] * W_{k-1}[k, j]).',
    actionLink: { view: 'relation', tab: 'closure' },
  },
  {
    id: 'rel_q23',
    topic: 'relation',
    topicName: 'Ma trận đối xứng',
    difficulty: 'easy',
    question: 'Nếu quan hệ R trên tập A có ma trận Boolean đối xứng qua đường chéo chính (M_R = M_Rᵀ) thì R có tính chất gì?',
    options: [
      { id: 'A', text: 'Phản xạ' },
      { id: 'B', text: 'Phản đối xứng' },
      { id: 'C', text: 'Đối xứng' },
      { id: 'D', text: 'Bắc cầu' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 4 trang 9: M_R = M_Rᵀ đồng nghĩa với M_R[i, j] = M_R[j, i] với mọi i, j. Do đó quan hệ R có tính chất Đối xứng.',
    actionLink: { view: 'relation', tab: 'matrix' },
  },
  {
    id: 'rel_q24',
    topic: 'relation',
    topicName: 'Định lý phân hoạch tập hợp',
    difficulty: 'medium',
    question: 'Định lý về phân hoạch khẳng định: Các lớp tương đương của một quan hệ tương đương R trên tập A chia tập A thành:',
    options: [
      { id: 'A', text: 'Các tập con không rỗng, đôi một rời nhau và hợp của chúng bằng tập A' },
      { id: 'B', text: 'Các tập con có ít nhất 2 phần tử chung' },
      { id: 'C', text: 'Một tập rỗng duy nhất' },
      { id: 'D', text: 'Các tập con có số lượng phần tử bằng nhau' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 4 trang 19-20: Các lớp tương đương tạo nên một phân hoạch trên A, nghĩa là chúng chia A thành các tập con không rỗng, đôi một rời nhau ([a] ∩ [b] = ∅ nếu [a] ≠ [b]) và hợp lại bằng toàn bộ A.',
    actionLink: { view: 'relation', tab: 'equivalence' },
  },
  {
    id: 'rel_q25',
    topic: 'relation',
    topicName: 'Kiểm tra tính bắc cầu',
    difficulty: 'medium',
    question: 'Cho tập A = {1, 2, 3, 4} và quan hệ R = {(1, 2), (2, 3)}. Để R có tính chất bắc cầu, ta bắt buộc phải bổ sung thêm cặp phần tử nào vào R?',
    options: [
      { id: 'A', text: '(2, 1)' },
      { id: 'B', text: '(1, 3)' },
      { id: 'C', text: '(3, 2)' },
      { id: 'D', text: '(1, 1)' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 4 trang 11: Do (1, 2) ∈ R và (2, 3) ∈ R, theo điều kiện bắc cầu bắt buộc phải có cặp (1, 3) ∈ R.',
    actionLink: { view: 'relation', tab: 'properties' },
  },

  // =========================================================================
  // CHƯƠNG 5: LÝ THUYẾT ĐỒ THỊ, EULER, HAMILTON, CÂY & CÁC THUẬT TOÁN
  // =========================================================================
  {
    id: 'graph_q01',
    topic: 'graph',
    topicName: 'Định lý Bắt tay',
    difficulty: 'easy',
    question: 'Một đơn đồ thị vô hướng có 5 đỉnh với bậc lần lượt là 2, 3, 3, 4, 4. Tổng số cạnh của đồ thị này là bao nhiêu?',
    options: [
      { id: 'A', text: '8 cạnh' },
      { id: 'B', text: '16 cạnh' },
      { id: 'C', text: '10 cạnh' },
      { id: 'D', text: '7 cạnh' },
    ],
    correctId: 'A',
    explanation: 'Theo Định lý bắt tay ở slide Chương 5 trang 13: Tổng bậc của tất cả các đỉnh bằng 2 lần số cạnh (∑ deg(v) = 2|E|). Tổng bậc = 2 + 3 + 3 + 4 + 4 = 16. Do đó số cạnh |E| = 16 / 2 = 8 cạnh.',
  },
  {
    id: 'graph_q02',
    topic: 'graph',
    topicName: 'Khuyên và bậc của đỉnh',
    difficulty: 'easy',
    question: 'Trong đồ thị vô hướng, cạnh nối một đỉnh với chính nó được gọi là gì và đóng góp bao nhiêu vào bậc của đỉnh đó?',
    options: [
      { id: 'A', text: 'Cạnh song song, tính 1 bậc' },
      { id: 'B', text: 'Khuyên (loop), tính 2 bậc' },
      { id: 'C', text: 'Cạnh treo, tính 1 bậc' },
      { id: 'D', text: 'Cầu, tính 0 bậc' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 6 và 11: Cạnh nối một đỉnh với chính nó gọi là khuyên. Riêng khuyên tại một đỉnh được tính hai lần cho bậc của nó.',
  },
  {
    id: 'graph_q03',
    topic: 'graph',
    topicName: 'Hệ quả số đỉnh bậc lẻ',
    difficulty: 'easy',
    question: 'Hệ quả trực tiếp của Định lý Bắt tay (Handshaking Theorem) trong đồ thị vô hướng là gì?',
    options: [
      { id: 'A', text: 'Mọi đỉnh đều có bậc chẵn' },
      { id: 'B', text: 'Số cạnh luôn là số chẵn' },
      { id: 'C', text: 'Trong mọi đồ thị vô hướng, số đỉnh có bậc lẻ luôn là một số chẵn' },
      { id: 'D', text: 'Đồ thị luôn có ít nhất một đỉnh cô lập' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 5 trang 13: Vì tổng bậc của tất cả các đỉnh luôn bằng 2|E| (số chẵn), nên số lượng đỉnh có bậc lẻ bắt buộc phải là một số chẵn để tổng không bị lẻ.',
  },
  {
    id: 'graph_q04',
    topic: 'graph',
    topicName: 'Bán bậc đồ thị có hướng',
    difficulty: 'easy',
    question: 'Trong đồ thị có hướng G = (V, E), định lý về tổng bán bậc khẳng định hệ thức nào sau đây?',
    options: [
      { id: 'A', text: '∑ deg⁺(v) = 2|E|' },
      { id: 'B', text: '∑ deg⁺(v) = ∑ deg⁻(v) = |E|' },
      { id: 'C', text: '∑ deg⁺(v) + ∑ deg⁻(v) = |E|' },
      { id: 'D', text: 'deg⁺(v) = deg⁻(v) với mọi đỉnh' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 14: Trong đồ thị có hướng, mỗi cung e = (u, v) đi ra khỏi đúng 1 đỉnh u (đóng góp 1 vào deg⁺) và đi vào đúng 1 đỉnh v (đóng góp 1 vào deg⁻). Do đó: ∑ deg⁺(v) = ∑ deg⁻(v) = |E|.',
  },
  {
    id: 'graph_q05',
    topic: 'graph',
    topicName: 'Đỉnh treo và Đỉnh cô lập',
    difficulty: 'easy',
    question: 'Một đỉnh v trong đồ thị vô hướng có bậc deg(v) = 1 được gọi là loại đỉnh gì?',
    options: [
      { id: 'A', text: 'Đỉnh treo' },
      { id: 'B', text: 'Đỉnh cô lập' },
      { id: 'C', text: 'Đỉnh khớp' },
      { id: 'D', text: 'Đỉnh Euler' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 11 quy định rõ: deg(v) = 1 gọi là đỉnh treo; deg(v) = 0 gọi là đỉnh cô lập.',
  },
  {
    id: 'euler_q01',
    topic: 'graph',
    topicName: 'Định lý Chu trình Euler',
    difficulty: 'easy',
    question: 'Định lý Euler khẳng định: Một đồ thị vô hướng liên thông có Chu trình Euler khi và chỉ khi:',
    options: [
      { id: 'A', text: 'Có đúng 2 đỉnh bậc lẻ' },
      { id: 'B', text: 'Mọi đỉnh đều có bậc chẵn (khác 0)' },
      { id: 'C', text: 'Có ít nhất một đỉnh bậc chẵn' },
      { id: 'D', text: 'Số cạnh bằng số đỉnh trừ 1' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 35: Đồ thị vô hướng liên thông có chu trình Euler khi và chỉ khi mọi đỉnh của nó đều có bậc chẵn khác 0.',
    actionLink: { view: 'lab', algoKey: 'euler' },
  },
  {
    id: 'euler_q02',
    topic: 'graph',
    topicName: 'Đường đi Euler',
    difficulty: 'easy',
    question: 'Một đồ thị vô hướng liên thông có Đường đi Euler (mở, vẽ được một nét không quay về đỉnh xuất phát) khi và chỉ khi:',
    options: [
      { id: 'A', text: 'Có đúng 2 đỉnh bậc lẻ' },
      { id: 'B', text: 'Mọi đỉnh đều có bậc lẻ' },
      { id: 'C', text: 'Có đúng 1 đỉnh bậc lẻ' },
      { id: 'D', text: 'Không có đỉnh bậc chẵn nào' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 35: Đồ thị vô hướng liên thông có đường đi Euler (không đóng) khi và chỉ khi nó có đúng 2 đỉnh bậc lẻ (2 đỉnh này chính là đỉnh xuất phát và đỉnh kết thúc của đường đi).',
    actionLink: { view: 'lab', algoKey: 'euler' },
  },
  {
    id: 'euler_q03',
    topic: 'graph',
    topicName: 'Thuật toán Fleury',
    difficulty: 'medium',
    question: 'Trong thuật toán Fleury tìm chu trình Euler, quy tắc cốt lõi khi chọn cạnh đi tiếp là gì?',
    options: [
      { id: 'A', text: 'Chỉ đi qua cạnh cầu (bridge) nếu không còn cạnh nào khác để chọn' },
      { id: 'B', text: 'Luôn ưu tiên chọn cạnh cầu đầu tiên' },
      { id: 'C', text: 'Luôn chọn cạnh có trọng số lớn nhất' },
      { id: 'D', text: 'Đi qua cạnh có đỉnh bậc lẻ trước' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 38: Thuật toán Fleury quy định nguyên tắc: "Chỉ chọn cạnh cầu nếu không còn cạnh nào khác để chọn. Bổ sung cạnh vừa chọn vào chu trình và xóa cạnh ấy khỏi đồ thị".',
    actionLink: { view: 'lab', algoKey: 'euler' },
  },
  {
    id: 'hamilton_q01',
    topic: 'graph',
    topicName: 'Định nghĩa Chu trình Hamilton',
    difficulty: 'easy',
    question: 'Khái niệm Chu trình Hamilton trong đồ thị được định nghĩa là chu trình:',
    options: [
      { id: 'A', text: 'Đi qua mọi cạnh đúng một lần rồi quay về đỉnh ban đầu' },
      { id: 'B', text: 'Đi qua mọi đỉnh đúng một lần rồi quay về đỉnh ban đầu' },
      { id: 'C', text: 'Đi qua ít nhất một nửa số đỉnh' },
      { id: 'D', text: 'Có độ dài ngắn nhất trong đồ thị' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 42: Chu trình Hamilton là chu trình bắt đầu từ một đỉnh v, đi qua tất cả các đỉnh còn lại mỗi đỉnh đúng một lần rồi quay trở về v.',
    actionLink: { view: 'lab', algoKey: 'hamilton' },
  },
  {
    id: 'hamilton_q02',
    topic: 'graph',
    topicName: 'Định lý Dirac (Hamilton)',
    difficulty: 'medium',
    question: 'Định lý Dirac (1952) khẳng định điều kiện đủ để đơn đồ thị có n đỉnh (n ≥ 3) là đồ thị Hamilton là gì?',
    options: [
      { id: 'A', text: 'Mọi đỉnh của đồ thị đều có bậc deg(v) ≥ n/2' },
      { id: 'B', text: 'Mọi đỉnh đều có bậc chẵn' },
      { id: 'C', text: 'Tổng số cạnh |E| ≥ n²' },
      { id: 'D', text: 'Đồ thị không chứa chu trình tam giác' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 45: Định lý Dirac (1952): Nếu G là đơn đồ thị có n đỉnh (n ≥ 3) và mỗi đỉnh của G đều có bậc không nhỏ hơn n/2 thì G là một đồ thị Hamilton.',
    actionLink: { view: 'lab', algoKey: 'hamilton' },
  },
  {
    id: 'mst_q01',
    topic: 'graph',
    topicName: 'Số cạnh của Cây (Tree)',
    difficulty: 'easy',
    question: 'Một Cây (Tree) có n đỉnh (n ≥ 1) luôn có chính xác bao nhiêu cạnh?',
    options: [
      { id: 'A', text: 'n cạnh' },
      { id: 'B', text: 'n - 1 cạnh' },
      { id: 'C', text: 'n + 1 cạnh' },
      { id: 'D', text: '2n cạnh' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 48: Định lý: Đơn đồ thị T là một cây n đỉnh khi và chỉ khi T liên thông và có đúng n - 1 cạnh (không chứa chu trình).',
  },
  {
    id: 'mst_q02',
    topic: 'graph',
    topicName: 'Thuật toán Kruskal',
    difficulty: 'easy',
    question: 'Đặc điểm cơ bản của thuật toán Kruskal tìm cây khung nhỏ nhất (MST) là:',
    options: [
      { id: 'A', text: 'Sắp xếp các cạnh tăng dần theo trọng số, lần lượt kết nạp cạnh nhỏ nhất không tạo thành chu trình' },
      { id: 'B', text: 'Bắt đầu từ 1 đỉnh và loang dần sang các đỉnh lân cận' },
      { id: 'C', text: 'Tìm đường đi ngắn nhất giữa từng cặp đỉnh' },
      { id: 'D', text: 'Xóa dần các đỉnh có bậc lớn nhất' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 58: Thuật toán Kruskal ưu tiên các cạnh có trọng số nhỏ hơn, kết nạp cạnh khi nó không tạo chu trình với tập cạnh đã chọn trước đó cho đến khi đủ n - 1 cạnh.',
    actionLink: { view: 'lab', algoKey: 'kruskal' },
  },
  {
    id: 'mst_q03',
    topic: 'graph',
    topicName: 'Thuật toán Prim',
    difficulty: 'medium',
    question: 'Đặc điểm cơ bản của thuật toán Prim tìm cây khung nhỏ nhất (MST) là:',
    options: [
      { id: 'A', text: 'Bắt đầu từ một đỉnh và mở rộng từng bước bằng cạnh có trọng số nhỏ nhất nối đỉnh đã xét với đỉnh chưa xét' },
      { id: 'B', text: 'Xét tất cả các cạnh theo thứ tự giảm dần trọng số' },
      { id: 'C', text: 'Chia đồ thị thành hai phần bằng nhau' },
      { id: 'D', text: 'Xóa cạnh cầu' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 56: Thuật toán Prim xuất phát từ một cây chỉ chứa đúng 1 đỉnh và mở rộng từng bước một, mỗi bước thêm một cạnh có trọng số nhỏ nhất nối cây hiện tại với một đỉnh ngoài cây.',
    actionLink: { view: 'lab', algoKey: 'prim' },
  },
  {
    id: 'dijkstra_q01',
    topic: 'graph',
    topicName: 'Điều kiện thuật toán Dijkstra',
    difficulty: 'easy',
    question: 'Điều kiện tiên quyết để thuật toán Dijkstra đảm bảo tìm được đường đi ngắn nhất chính xác là gì?',
    options: [
      { id: 'A', text: 'Đồ thị phải là đồ thị phẳng' },
      { id: 'B', text: 'Trọng số của tất cả các cạnh phải không âm (w(e) ≥ 0)' },
      { id: 'C', text: 'Đồ thị phải là đồ thị có hướng phi chu trình (DAG)' },
      { id: 'D', text: 'Mọi đỉnh phải có bậc chẵn' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 61: Thuật toán Dijkstra tìm đường đi ngắn nhất trong đồ thị có trọng số w(i, j) > 0 (không âm). Nếu có cạnh âm, giả định tối ưu Greedy bị phá vỡ.',
    actionLink: { view: 'lab', algoKey: 'dijkstra' },
  },
  {
    id: 'dijkstra_q02',
    topic: 'graph',
    topicName: 'Công thức cập nhật nhãn Dijkstra',
    difficulty: 'medium',
    question: 'Trong thuật toán Dijkstra, bước cập nhật nhãn khoảng cách khi xét đỉnh x kề với đỉnh v vừa cố định (relaxation) được thực hiện theo công thức nào?',
    options: [
      { id: 'A', text: 'L(x) = min{L(x), L(v) + w(v, x)}' },
      { id: 'B', text: 'L(x) = L(x) + w(v, x)' },
      { id: 'C', text: 'L(x) = max{L(x), L(v) + w(v, x)}' },
      { id: 'D', text: 'L(x) = w(v, x)' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 62 (Bước 4 thuật toán Dijkstra): Với mỗi x ∈ T kề với v, cập nhật: L(x) = min{L(x), L(v) + w(v, x)}.',
    actionLink: { view: 'lab', algoKey: 'dijkstra' },
  },
  {
    id: 'dijkstra_q03',
    topic: 'graph',
    topicName: 'Khởi tạo nhãn Dijkstra',
    difficulty: 'easy',
    question: 'Khi khởi tạo thuật toán Dijkstra với đỉnh nguồn a, nhãn khoảng cách ban đầu L(a) của a và L(x) của các đỉnh x ≠ a được gán lần lượt là:',
    options: [
      { id: 'A', text: 'L(a) = ∞ và L(x) = 0' },
      { id: 'B', text: 'L(a) = 0 và L(x) = ∞' },
      { id: 'C', text: 'L(a) = 1 và L(x) = 0' },
      { id: 'D', text: 'L(a) = 0 và L(x) = 1' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 62 (Bước 1 thuật toán Dijkstra): Gán L(a) = 0. Với mọi đỉnh x ≠ a gán L(x) = ∞.',
    actionLink: { view: 'lab', algoKey: 'dijkstra' },
  },
  {
    id: 'graph_q06',
    topic: 'graph',
    topicName: 'Ma trận kề đồ thị vô hướng',
    difficulty: 'easy',
    question: 'Ma trận kề của một đơn đồ thị vô hướng có n đỉnh luôn có tính chất gì?',
    options: [
      { id: 'A', text: 'Là ma trận đối xứng và có đường chéo chính toàn số 0' },
      { id: 'B', text: 'Là ma trận tam giác trên' },
      { id: 'C', text: 'Không đối xứng' },
      { id: 'D', text: 'Có đường chéo chính toàn số 1' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 21-22: Vì cạnh (u, v) vô hướng nên a_ij = a_ji (ma trận đối xứng). Đơn đồ thị không có khuyên nên đường chéo chính a_ii = 0 với mọi i.',
  },
  {
    id: 'graph_q07',
    topic: 'graph',
    topicName: 'Ma trận liên thuộc',
    difficulty: 'easy',
    question: 'Trong ma trận liên thuộc (đỉnh - cạnh) của một đồ thị vô hướng, mỗi cột có đúng bao nhiêu phần tử bằng 1?',
    options: [
      { id: 'A', text: '1 phần tử' },
      { id: 'B', text: '0 phần tử' },
      { id: 'C', text: '2 phần tử (tương ứng 2 đầu mút của cạnh)' },
      { id: 'D', text: 'n phần tử' },
    ],
    correctId: 'C',
    explanation: 'Slide Chương 5 trang 23: Mỗi cột biểu diễn 1 cạnh. Cạnh vô hướng nối 2 đỉnh phân biệt nên ở mỗi cột có đúng hai số 1 tại hai hàng tương ứng hai đỉnh đầu mút.',
  },
  {
    id: 'graph_q08',
    topic: 'graph',
    topicName: 'Đỉnh treo trong Cây',
    difficulty: 'medium',
    question: 'Một đồ thị vô hướng T có n đỉnh (n ≥ 2) là một cây (Tree) thì chắc chắn chứa ít nhất bao nhiêu đỉnh treo (đỉnh bậc 1)?',
    options: [
      { id: 'A', text: 'Ít nhất 2 đỉnh treo' },
      { id: 'B', text: 'Ít nhất 1 đỉnh treo' },
      { id: 'C', text: 'Không có đỉnh treo nào' },
      { id: 'D', text: 'Đúng n đỉnh treo' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 48: Định lý: Nếu 1 cây T gồm n đỉnh với n ≥ 2 thì T chứa ít nhất 2 đỉnh treo (đỉnh có deg(v) = 1).',
  },
  {
    id: 'graph_q09',
    topic: 'graph',
    topicName: 'Đồ thị đầy đủ K_n',
    difficulty: 'easy',
    question: 'Đồ thị đầy đủ K_n với n đỉnh có tổng cộng bao nhiêu cạnh?',
    options: [
      { id: 'A', text: 'n(n - 1) / 2 cạnh' },
      { id: 'B', text: 'n cạnh' },
      { id: 'C', text: 'n² cạnh' },
      { id: 'D', text: 'n(n + 1) / 2 cạnh' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 7: Đồ thị đủ K_n là đơn đồ thị mà 2 đỉnh bất kỳ luôn kề nhau. Số cạnh bằng số cặp đỉnh: C(n, 2) = n(n - 1) / 2 cạnh.',
  },
  {
    id: 'graph_q10',
    topic: 'graph',
    topicName: 'Đồ thị hai phía (Lưỡng phân)',
    difficulty: 'easy',
    question: 'Đồ thị hai phía (bipartite graph) là đồ thị có tập đỉnh V có thể chia thành hai tập con V₁ và V₂ rời nhau sao cho:',
    options: [
      { id: 'A', text: 'Mọi cạnh đều nằm trong tập V₁' },
      { id: 'B', text: 'Mọi cạnh của đồ thị chỉ nối một đỉnh thuộc V₁ với một đỉnh thuộc V₂ (không có cạnh nối hai đỉnh cùng thuộc một tập)' },
      { id: 'C', text: 'Có cạnh nối giữa mọi cặp đỉnh trong V₁' },
      { id: 'D', text: 'Đồ thị có chu trình độ dài lẻ' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 8: Định nghĩa đồ thị hai phía: tập đỉnh được chia thành 2 tập không giao nhau V₁, V₂ sao cho không có cạnh nào nối 2 đỉnh thuộc cùng một tập.',
  },
  {
    id: 'graph_q11',
    topic: 'graph',
    topicName: 'Nhận biết Cây theo số cạnh',
    difficulty: 'medium',
    question: 'Một đồ thị vô hướng liên thông có 6 đỉnh và 5 cạnh. Khẳng định nào sau đây chắc chắn đúng về đồ thị này?',
    options: [
      { id: 'A', text: 'Đồ thị này là một cây (Tree) và không chứa chu trình' },
      { id: 'B', text: 'Đồ thị có chu trình Euler' },
      { id: 'C', text: 'Đồ thị có chu trình Hamilton' },
      { id: 'D', text: 'Đồ thị không liên thông' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 48: Đơn đồ thị T có n đỉnh là một cây khi và chỉ khi T liên thông và có đúng n - 1 cạnh. Ở đây n = 6 và số cạnh là 5, nên đồ thị chắc chắn là một Cây.',
  },
  {
    id: 'hamilton_q03',
    topic: 'graph',
    topicName: 'Điều kiện đỉnh bậc trong Hamilton',
    difficulty: 'easy',
    question: 'Nếu một đồ thị vô hướng chứa một đỉnh v có bậc deg(v) = 1 (đỉnh treo) thì đồ thị đó có chu trình Hamilton hay không?',
    options: [
      { id: 'A', text: 'Không thể có chu trình Hamilton (vì chu trình Hamilton đòi hỏi mọi đỉnh có bậc ít nhất là 2)' },
      { id: 'B', text: 'Chắc chắn có chu trình Hamilton' },
      { id: 'C', text: 'Luôn có chu trình Euler' },
      { id: 'D', text: 'Tùy thuộc vào số đỉnh còn lại' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 46: Quy tắc xác định chu trình Hamilton: "Nếu G có đỉnh bậc < 2 thì G không có chu trình Hamilton", vì chu trình Hamilton phải đi vào và đi ra khỏi mỗi đỉnh qua 2 cạnh phân biệt.',
    actionLink: { view: 'lab', algoKey: 'hamilton' },
  },
  {
    id: 'mst_q04',
    topic: 'graph',
    topicName: 'Số cạnh của Cây khung',
    difficulty: 'medium',
    question: 'Cho đồ thị liên thông G có 7 đỉnh. Bất kỳ cây khung (Spanning tree) nào của G cũng phải chứa đúng bao nhiêu cạnh?',
    options: [
      { id: 'A', text: '6 cạnh (n - 1)' },
      { id: 'B', text: '7 cạnh' },
      { id: 'C', text: '5 cạnh' },
      { id: 'D', text: '12 cạnh' },
    ],
    correctId: 'A',
    explanation: 'Slide Chương 5 trang 52: Cây khung của đồ thị n đỉnh là đồ thị con chứa toàn bộ n đỉnh, liên thông và không có chu trình. Mọi cây n đỉnh đều có đúng n - 1 cạnh. Với n = 7, cây khung có đúng 7 - 1 = 6 cạnh.',
    actionLink: { view: 'lab', algoKey: 'kruskal' },
  },
  {
    id: 'dijkstra_q04',
    topic: 'graph',
    topicName: 'Trọng số âm & Bellman-Ford',
    difficulty: 'easy',
    question: 'Trong đồ thị có trọng số xuất hiện cạnh mang trọng số âm (w(e) < 0), thuật toán Dijkstra có thể cho kết quả sai. Thuật toán nào sau đây được học để thay thế trong trường hợp có trọng số âm?',
    options: [
      { id: 'A', text: 'Thuật toán Kruskal' },
      { id: 'B', text: 'Thuật toán Bellman-Ford' },
      { id: 'C', text: 'Thuật toán Prim' },
      { id: 'D', text: 'Thuật toán Fleury' },
    ],
    correctId: 'B',
    explanation: 'Slide Chương 5 trang 60: Thuật toán Bellman-Ford tìm đường đi ngắn nhất từ một nguồn trong đồ thị có thể chứa trọng số âm.',
    actionLink: { view: 'lab', algoKey: 'dijkstra' },
  },
];

/**
 * Procedurally generates an exam paper by drawing questions from STATIC_QUESTION_BANK.
 * 
 * @param {Object} [options={}]
 * @param {number} [options.count=5]
 * @param {string} [options.topic='all']
 * @param {string} [options.difficulty='all']
 * @returns {Object} Exam specification
 */
export function generateExamPaper({
  count = 5,
  topic = QUIZ_TOPICS.ALL,
  difficulty = QUIZ_DIFFICULTIES.ALL,
} = {}) {
  let pool = [...STATIC_QUESTION_BANK];

  if (topic !== QUIZ_TOPICS.ALL) {
    pool = pool.filter(q => q.topic === topic);
  }

  if (difficulty !== QUIZ_DIFFICULTIES.ALL) {
    pool = pool.filter(q => q.difficulty === difficulty);
  }

  // Fallback if pool is smaller than requested count
  if (pool.length === 0) {
    pool = [...STATIC_QUESTION_BANK];
  }

  // Shuffle pool using Fisher-Yates
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  const selectedQuestions = shuffled.slice(0, Math.min(count, shuffled.length));
  const examCode = Math.floor(100 + Math.random() * 900);

  const answerKey = {};
  selectedQuestions.forEach((q, idx) => {
    answerKey[idx + 1] = q.correctId;
  });

  return {
    examCode,
    topic,
    difficulty,
    createdAt: new Date().toLocaleDateString('vi-VN'),
    totalQuestions: selectedQuestions.length,
    questions: selectedQuestions,
    answerKey,
  };
}

/**
 * Exports an examination paper into clean, standard LaTeX format.
 * Suitable for university exam papers (amsmath, geometry, enumerate).
 * 
 * @param {Object} exam
 * @returns {string} LaTeX source code
 */
export function exportExamToLatex(exam) {
  let latex = `% ==========================================================================\n`;
  latex += `% ĐỀ THI TRẮC NGHIỆM MÔN TOÁN RỜI RẠC & CẤU TRÚC RỜI RẠC\n`;
  latex += `% Mã đề: ${exam.examCode} — Ngày tạo: ${exam.createdAt}\n`;
  latex += `% Nền tảng: Graph Algorithms & Logic Platform (EdTech Interactive Suite)\n`;
  latex += `% ==========================================================================\n\n`;

  latex += `\\documentclass[12pt,a4paper]{article}\n`;
  latex += `\\usepackage[utf8]{inputenc}\n`;
  latex += `\\usepackage[vietnamese]{babel}\n`;
  latex += `\\usepackage{amsmath,amssymb,amsfonts}\n`;
  latex += `\\usepackage{geometry}\n`;
  latex += `\\geometry{left=2cm,right=2cm,top=2cm,bottom=2cm}\n`;
  latex += `\\usepackage{enumerate}\n`;
  latex += `\\usepackage{multicol}\n\n`;

  latex += `\\begin{document}\n\n`;

  // Header Box
  latex += `\\noindent\n`;
  latex += `\\begin{tabular}{@{}p{8.5cm}p{8.5cm}@{}}\n`;
  latex += `  \\textbf{TRƯỜNG ĐẠI HỌC ...........................} & \\textbf{ĐỀ THI MÔN: TOÁN RỜI RẠC} \\\\\n`;
  latex += `  \\textbf{KHOA CÔNG NGHỆ THÔNG TIN} & \\textbf{Thời gian làm bài:} 45 phút \\\\\n`;
  latex += `  \\textit{Họ và tên thí sinh:} .................................... & \\textbf{MÃ ĐỀ THI: ${exam.examCode}} \\\\\n`;
  latex += `  \\textit{Mã số sinh viên (MSSV):} ........................... & \\textit{Lớp:} .................................... \\\\\n`;
  latex += `\\end{tabular}\n\n`;
  latex += `\\vspace{0.3cm}\n`;
  latex += `\\hrule height 1pt\n`;
  latex += `\\vspace{0.4cm}\n\n`;

  // Questions
  latex += `\\section*{PHẦN CÂU HỎI TRẮC NGHIỆM (${exam.totalQuestions} CÂU)}\n\n`;
  latex += `\\begin{enumerate}[\\bfseries Câu 1:]\n`;

  exam.questions.forEach((q) => {
    // Strip HTML svg tags from question text for LaTeX export
    const cleanQuestion = q.question.replace(/<br><svg[\s\S]*?<\/svg>/gi, ' (Quan sát hình vẽ đính kèm trong đề thi)').replace(/<[^>]+>/g, '');
    latex += `  \\item ${cleanQuestion}\n`;
    latex += `  \\begin{multicols}{2}\n`;
    latex += `  \\begin{enumerate}[A.]\n`;
    q.options.forEach((opt) => {
      latex += `    \\item ${opt.text}\n`;
    });
    latex += `  \\end{enumerate}\n`;
    latex += `  \\end{multicols}\n\n`;
  });

  latex += `\\end{enumerate}\n\n`;

  // Page break for Teacher Answer Key
  latex += `\\newpage\n`;
  latex += `\\section*{ĐÁP ÁN & HƯỚNG DẪN CHẤM (DÀNH CHO GIẢNG VIÊN - MÃ ĐỀ: ${exam.examCode})}\n\n`;

  // Fast Answer Grid Table
  latex += `\\subsection*{1. Bảng Đáp Án Nhanh}\n`;
  latex += `\\begin{center}\n`;
  latex += `\\begin{tabular}{|${exam.questions.map(() => 'c|').join('')}}\n\\hline\n`;
  latex += `\\textbf{Câu} & ${exam.questions.map((_, i) => `\\textbf{${i + 1}}`).join(' & ')} \\\\\n\\hline\n`;
  latex += `\\textbf{Đáp án} & ${exam.questions.map((q) => `\\textbf{${q.correctId}}`).join(' & ')} \\\\\n\\hline\n`;
  latex += `\\end{tabular}\n`;
  latex += `\\end{center}\n\n`;

  // Detailed Explanations
  latex += `\\subsection*{2. Hướng Dẫn Lời Giải Chi Tiết}\n`;
  latex += `\\begin{enumerate}[\\bfseries Câu 1:]\n`;
  exam.questions.forEach((q) => {
    latex += `  \\item \\textbf{Đáp án ${q.correctId}.} ${q.explanation}\n\n`;
  });
  latex += `\\end{enumerate}\n\n`;

  latex += `\\end{document}\n`;

  return latex;
}
