/**
 * @file PlaybackController.js
 * Headless, deterministic playback and stepping controller for algorithm traces.
 *
 * Fully DOM-independent, pure ES Module.
 * Consumes AlgorithmStep[] generated by Phase 2 Core Algorithm Engines.
 *
 * Provides:
 * - Deterministic navigation (goto, next, prev, first, last)
 * - Timer-driven autoplay with Timer Dependency Injection
 * - Clean separation between timer advancement and manual navigation
 * - Search and skipping (skipTo, skipToAction, skipToNextSettled)
 * - Subscriber state notifications
 * - Strict input immutability
 */

import { AlgorithmAction } from '../../core/models/Types.js';

/**
 * Default milestone actions representing meaningful algorithm progress steps.
 * Covers:
 * - Dijkstra: SELECT_NODE, FINISH
 * - Kruskal: ACCEPT_EDGE, FINISH
 * - Prim: SELECT_NODE, ACCEPT_EDGE, FINISH
 * - Euler: SELECT_NODE, ACCEPT_EDGE, FINISH
 * - Hamilton: SELECT_NODE, FINISH
 */
const DEFAULT_SETTLED_ACTIONS = Object.freeze([
  AlgorithmAction.SELECT_NODE,
  AlgorithmAction.ACCEPT_EDGE,
  AlgorithmAction.FINISH,
  AlgorithmAction.ERROR,
]);

/**
 * Controller managing step-by-step playback, navigation, and autoplay for AlgorithmStep sequences.
 */
export class PlaybackController {
  /**
   * @param {Object} [options={}] - Configuration options
   * @param {Array<Object>} [options.steps=[]] - Initial algorithm steps
   * @param {number} [options.speed=1000] - Interval speed in ms
   * @param {number} [options.playSpeed] - Alias for speed
   * @param {number} [options.initialIndex=0] - Starting step index if steps are provided
   * @param {Object} [options.timer] - Timer DI { setInterval, clearInterval }
   */
  constructor(options = {}) {
    const {
      steps = [],
      speed = 1000,
      playSpeed,
      initialIndex = 0,
      timer,
    } = options;

    // Timer Dependency Injection
    this._timer = {
      setInterval:
        timer && typeof timer.setInterval === 'function'
          ? timer.setInterval.bind(timer)
          : globalThis.setInterval.bind(globalThis),
      clearInterval:
        timer && typeof timer.clearInterval === 'function'
          ? timer.clearInterval.bind(timer)
          : globalThis.clearInterval.bind(globalThis),
    };

    const initialSpeed = playSpeed !== undefined ? playSpeed : speed;
    if (typeof initialSpeed !== 'number' || Number.isNaN(initialSpeed) || initialSpeed <= 0) {
      throw new RangeError(
        `Playback speed must be a positive number, received ${initialSpeed}`
      );
    }
    this._playSpeed = initialSpeed;

    this._steps = [];
    this._currentIndex = -1;
    this._isPlaying = false;
    this._timerId = null;
    this._subscribers = new Set();
    this._isDestroyed = false;

    if (Array.isArray(steps) && steps.length > 0) {
      this.loadSteps(steps, initialIndex);
    }
  }

  // =========================================================================
  // STATE GETTERS
  // =========================================================================

  /**
   * Retrieves a copy of the loaded steps array.
   * @returns {Array<Object>}
   */
  get steps() {
    return [...this._steps];
  }

  /**
   * Current 0-based step index (-1 if empty).
   * @returns {number}
   */
  get currentIndex() {
    return this._currentIndex;
  }

  /**
   * Reference to the currently active step (null if empty).
   * @returns {Object|null}
   */
  get currentStep() {
    if (this._currentIndex >= 0 && this._currentIndex < this._steps.length) {
      return this._steps[this._currentIndex];
    }
    return null;
  }

  /**
   * Whether autoplay interval timer is actively running.
   * @returns {boolean}
   */
  get isPlaying() {
    return this._isPlaying;
  }

  /**
   * Playback speed in milliseconds per step.
   * @returns {number}
   */
  get playSpeed() {
    return this._playSpeed;
  }

  /**
   * Total number of loaded steps.
   * @returns {number}
   */
  get totalSteps() {
    return this._steps.length;
  }

  get stepCount() {
    return this._steps.length;
  }

  get currentStepIndex() {
    return this._currentIndex;
  }

  load(steps, initialIndex = 0) {
    return this.loadSteps(steps, initialIndex);
  }

  seek(index) {
    return this.goto(index);
  }

  stepForward() {
    return this.next();
  }

  stepBackward() {
    return this.prev();
  }

  /**
   * True if at or before the first step (or if empty).
   * @returns {boolean}
   */
  get isAtStart() {
    return this._steps.length === 0 || this._currentIndex <= 0;
  }

  /**
   * True if at or beyond the last step (or if empty).
   * @returns {boolean}
   */
  get isAtEnd() {
    return this._steps.length === 0 || this._currentIndex >= this._steps.length - 1;
  }

  /**
   * Returns a snapshot object of the current playback state.
   * @returns {Object}
   */
  getState() {
    return {
      steps: [...this._steps],
      currentIndex: this._currentIndex,
      currentStep: this.currentStep,
      isPlaying: this._isPlaying,
      playSpeed: this._playSpeed,
      totalSteps: this.totalSteps,
      isAtStart: this.isAtStart,
      isAtEnd: this.isAtEnd,
    };
  }

  // =========================================================================
  // STEP LOADING & RESET
  // =========================================================================

  /**
   * Loads a new sequence of algorithm steps into the controller.
   * Pauses active playback and resets index safely.
   *
   * @param {Array<Object>} steps - Array of AlgorithmStep objects
   * @param {number} [initialIndex=0] - Initial step index
   * @returns {Object|null} The newly active currentStep
   */
  loadSteps(steps, initialIndex = 0) {
    this.pause();

    if (!Array.isArray(steps) || steps.length === 0) {
      this._steps = [];
      this._currentIndex = -1;
    } else {
      // Shallow copy container to prevent external mutation of controller state
      this._steps = [...steps];
      this._currentIndex = Math.max(0, Math.min(this._steps.length - 1, initialIndex));
    }

    this._notify();
    return this.currentStep;
  }

  /**
   * Clears all steps and resets controller to empty state.
   */
  clear() {
    this.pause();
    this._steps = [];
    this._currentIndex = -1;
    this._notify();
  }

  // =========================================================================
  // NAVIGATION
  // =========================================================================

  /**
   * Jumps to a specific step index, clamped to [0, steps.length - 1].
   * Does not pause autoplay.
   *
   * @param {number} index - Target index
   * @returns {Object|null} Newly active currentStep
   */
  goto(index) {
    if (this._steps.length === 0) {
      return null;
    }

    const clamped = Math.max(0, Math.min(this._steps.length - 1, index));
    if (clamped !== this._currentIndex) {
      this._currentIndex = clamped;
      this._notify();
    }

    return this.currentStep;
  }

  /**
   * Advances one step forward. Clamps to end (no wrap-around).
   * Does not pause autoplay.
   *
   * @returns {Object|null} Newly active currentStep
   */
  next() {
    if (this._steps.length === 0) {
      return null;
    }
    if (this._currentIndex < this._steps.length - 1) {
      return this.goto(this._currentIndex + 1);
    }
    return this.currentStep;
  }

  /**
   * Moves one step backward. Clamps to start (no wrap-around).
   * Does not pause autoplay.
   *
   * @returns {Object|null} Newly active currentStep
   */
  prev() {
    if (this._steps.length === 0) {
      return null;
    }
    if (this._currentIndex > 0) {
      return this.goto(this._currentIndex - 1);
    }
    return this.currentStep;
  }

  /**
   * Jumps to the first step (index 0).
   *
   * @returns {Object|null} Newly active currentStep
   */
  first() {
    if (this._steps.length === 0) {
      return null;
    }
    return this.goto(0);
  }

  /**
   * Jumps to the last step (index steps.length - 1).
   *
   * @returns {Object|null} Newly active currentStep
   */
  last() {
    if (this._steps.length === 0) {
      return null;
    }
    return this.goto(this._steps.length - 1);
  }

  // =========================================================================
  // PLAYBACK & TIMER
  // =========================================================================

  /**
   * Starts autoplay interval.
   * - If at end, restarts from index 0 (legacy behavior).
   * - Idempotent if already playing.
   *
   * @returns {boolean} True if playback started or already active, false if cannot play
   */
  play() {
    if (this._steps.length === 0 || this._isDestroyed) {
      return false;
    }
    if (this._isPlaying) {
      return true;
    }

    // Auto-restart at 0 if sitting at the end (legacy behavior)
    if (this._currentIndex >= this._steps.length - 1) {
      this.goto(0);
    }

    this._isPlaying = true;
    this._timerId = this._timer.setInterval(() => this._tick(), this._playSpeed);
    this._notify();
    return true;
  }

  /**
   * Pauses active autoplay interval.
   * Idempotent if already paused.
   *
   * @returns {boolean} True if paused, false if was already paused
   */
  pause() {
    if (!this._isPlaying) {
      return false;
    }

    if (this._timerId !== null) {
      this._timer.clearInterval(this._timerId);
      this._timerId = null;
    }
    this._isPlaying = false;
    this._notify();
    return true;
  }

  /**
   * Toggles playback between playing and paused.
   *
   * @returns {boolean} New isPlaying status
   */
  togglePlay() {
    if (this._isPlaying) {
      this.pause();
    } else {
      this.play();
    }
    return this._isPlaying;
  }

  /**
   * Updates playback speed.
   * If currently playing, dynamically restarts the timer without resetting index.
   *
   * @param {number} speedMs - Milliseconds per step (> 0)
   */
  setSpeed(speedMs) {
    if (typeof speedMs !== 'number' || Number.isNaN(speedMs) || speedMs <= 0) {
      throw new RangeError(
        `Playback speed must be a positive number, received ${speedMs}`
      );
    }

    this._playSpeed = speedMs;

    if (this._isPlaying && this._timerId !== null) {
      this._timer.clearInterval(this._timerId);
      this._timerId = this._timer.setInterval(() => this._tick(), this._playSpeed);
    }

    this._notify();
  }

  /**
   * Internal timer tick. Advances by 1 step, or pauses upon reaching the end.
   * @private
   */
  _tick() {
    if (this._isDestroyed || !this._isPlaying) {
      return;
    }

    if (this._currentIndex < this._steps.length - 1) {
      this.goto(this._currentIndex + 1);
    } else {
      this.pause();
    }
  }

  // =========================================================================
  // SEARCH & SKIPPING
  // =========================================================================

  /**
   * Skips forward to the first step matching a custom predicate.
   *
   * @param {Function} predicate - (step, index, steps) => boolean
   * @param {Object} [options={}] - Search options
   * @param {number} [options.fromIndex] - Starting search index (defaults to currentIndex + 1)
   * @param {boolean} [options.clampToEnd=true] - If true, jumps to last step when no match found
   * @returns {Object|null} Matching step or terminal step (or null if empty / no match with clampToEnd=false)
   */
  skipTo(predicate, options = {}) {
    if (typeof predicate !== 'function') {
      throw new TypeError(`Predicate must be a function, received ${typeof predicate}`);
    }
    if (this._steps.length === 0) {
      return null;
    }

    const {
      fromIndex = this._currentIndex + 1,
      clampToEnd = true,
    } = options;

    const startIndex = Math.max(0, fromIndex);
    for (let i = startIndex; i < this._steps.length; i++) {
      if (predicate(this._steps[i], i, this._steps)) {
        return this.goto(i);
      }
    }

    // No match found
    if (clampToEnd !== false) {
      return this.goto(this._steps.length - 1);
    }

    return null;
  }

  /**
   * Skips forward to the next step matching one of the specified actions.
   *
   * @param {string|string[]} targetActions - Action name or array of action names
   * @param {Object} [options={}] - Search options
   * @returns {Object|null}
   */
  skipToAction(targetActions, options = {}) {
    if (!targetActions) {
      throw new TypeError('targetActions is required');
    }

    const actionsSet = new Set(
      Array.isArray(targetActions) ? targetActions : [targetActions]
    );

    return this.skipTo(
      (step) => Boolean(step && actionsSet.has(step.action)),
      options
    );
  }

  /**
   * Skips forward to the next settled milestone step.
   * Default milestones: SELECT_NODE, ACCEPT_EDGE, FINISH, ERROR.
   *
   * @param {Object} [options={}] - Search options
   * @returns {Object|null}
   */
  skipToNextSettled(options = {}) {
    return this.skipToAction(DEFAULT_SETTLED_ACTIONS, options);
  }

  // =========================================================================
  // SUBSCRIPTION & LIFECYCLE
  // =========================================================================

  /**
   * Registers a subscriber listener function to receive state updates.
   *
   * @param {Function} listener - (currentStep, state) => void
   * @returns {Function} Unsubscribe function
   */
  subscribe(listener) {
    if (typeof listener !== 'function') {
      throw new TypeError(
        `Subscriber listener must be a function, received ${typeof listener}`
      );
    }

    this._subscribers.add(listener);

    return () => {
      this._subscribers.delete(listener);
    };
  }

  /**
   * Destroys the controller instance, clears timers and unsubscribes all listeners.
   */
  destroy() {
    this.pause();
    this._subscribers.clear();
    this._steps = [];
    this._currentIndex = -1;
    this._isDestroyed = true;
  }

  /**
   * Notifies all subscribers of current state.
   * @private
   */
  _notify() {
    if (this._isDestroyed || this._subscribers.size === 0) {
      return;
    }

    const currentStep = this.currentStep;
    const state = this.getState();

    for (const listener of this._subscribers) {
      try {
        listener(currentStep, state);
      } catch (err) {
        // Isolate subscriber errors to ensure remaining subscribers still run
        console.error('PlaybackController subscriber error:', err);
      }
    }
  }
}

export default PlaybackController;
