/**
 * @file LogicPresets.js
 * Curated repository of classic propositional logic laws and benchmark expressions
 * widely taught in Discrete Mathematics courses.
 */

export const LOGIC_PRESETS = [
  {
    id: 'demorgan_1',
    name: 'Luật De Morgan (Hội sang Tuyển)',
    category: 'Tương đương kinh điển',
    expression: '¬(p ∧ q) ↔ (¬p ∨ ¬q)',
    variables: ['p', 'q'],
    description: 'Phủ định của một hội tương đương với tuyển các phủ định.',
  },
  {
    id: 'demorgan_2',
    name: 'Luật De Morgan (Tuyển sang Hội)',
    category: 'Tương đương kinh điển',
    expression: '¬(p ∨ q) ↔ (¬p ∧ ¬q)',
    variables: ['p', 'q'],
    description: 'Phủ định của một tuyển tương đương với hội các phủ định.',
  },
  {
    id: 'implication_law',
    name: 'Luật Kéo theo (Biến đổi về Tuyển)',
    category: 'Tương đương kinh điển',
    expression: '(p → q) ↔ (¬p ∨ q)',
    variables: ['p', 'q'],
    description: 'Biểu thức kéo theo p → q luôn tương đương với ¬p ∨ q.',
  },
  {
    id: 'contrapositive',
    name: 'Luật Phản đảo (Contrapositive)',
    category: 'Tương đương kinh điển',
    expression: '(p → q) ↔ (¬q → ¬p)',
    variables: ['p', 'q'],
    description: 'Mệnh đề kéo theo luôn tương đương với mệnh đề phản đảo của nó.',
  },
  {
    id: 'distributive_and',
    name: 'Luật Phân phối (Hội đối với Tuyển)',
    category: 'Tương đương kinh điển',
    expression: '(p ∧ (q ∨ r)) ↔ ((p ∧ q) ∨ (p ∧ r))',
    variables: ['p', 'q', 'r'],
    description: 'Phép hội phân phối đối với phép tuyển: p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r).',
  },
  {
    id: 'distributive_or',
    name: 'Luật Phân phối (Tuyển đối với Hội)',
    category: 'Tương đương kinh điển',
    expression: '(p ∨ (q ∧ r)) ↔ ((p ∨ q) ∧ (p ∨ r))',
    variables: ['p', 'q', 'r'],
    description: 'Phép tuyển phân phối đối với phép hội: p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r).',
  },
  {
    id: 'modus_ponens',
    name: 'Khẳng định tiền đề (Modus Ponens)',
    category: 'Quy tắc suy diễn (Hằng đúng)',
    expression: '((p → q) ∧ p) → q',
    variables: ['p', 'q'],
    description: 'Nếu p kéo theo q và p đúng thì suy ra q đúng (Quy tắc suy diễn cốt lõi).',
  },
  {
    id: 'modus_tollens',
    name: 'Phủ định hậu đề (Modus Tollens)',
    category: 'Quy tắc suy diễn (Hằng đúng)',
    expression: '((p → q) ∧ ¬q) → ¬p',
    variables: ['p', 'q'],
    description: 'Nếu p kéo theo q và q sai thì suy ra p cũng phải sai.',
  },
  {
    id: 'hypothetical_syllogism',
    name: 'Tam đoạn luận giả thiết (Bắc cầu kéo theo)',
    category: 'Quy tắc suy diễn (Hằng đúng)',
    expression: '((p → q) ∧ (q → r)) → (p → r)',
    variables: ['p', 'q', 'r'],
    description: 'Tính chất bắc cầu: nếu p → q và q → r thì chắc chắn p → r.',
  },
  {
    id: 'disjunctive_syllogism',
    name: 'Tam đoạn luận tuyển (Tuyển loại trừ)',
    category: 'Quy tắc suy diễn (Hằng đúng)',
    expression: '((p ∨ q) ∧ ¬p) → q',
    variables: ['p', 'q'],
    description: 'Hoặc p hoặc q đúng; nếu p sai thì bắt buộc q phải đúng.',
  },
  {
    id: 'absorption',
    name: 'Luật Hấp thụ (Absorption)',
    category: 'Tương đương kinh điển',
    expression: '(p ∨ (p ∧ q)) ↔ p',
    variables: ['p', 'q'],
    description: 'Mệnh đề p hấp thụ thành phần (p ∧ q) khi tuyển lại với nhau.',
  },
  {
    id: 'contradiction_simple',
    name: 'Mâu thuẫn cơ bản (Contradiction)',
    category: 'Hằng sai (Luôn sai)',
    expression: 'p ∧ ¬p',
    variables: ['p'],
    description: 'Một mệnh đề không thể vừa đúng vừa sai cùng một lúc.',
  },
  {
    id: 'sat_chain_4',
    name: 'Chuỗi hội logic 4 biến (SAT Chain)',
    category: 'Bài toán phức hợp (4 biến)',
    expression: '(p ∨ q) ∧ (¬q ∨ r) ∧ (¬r ∨ s) ∧ ¬s',
    variables: ['p', 'q', 'r', 's'],
    description: 'Hệ mệnh đề dạng CNF 4 biến kiểm tra khả năng thỏa được (SAT solver).',
  },
  // 5 Classic Circuit & K-Map Cases
  {
    id: 'case_sgk',
    name: 'Mạch Sách Giáo Khoa: Cổng AND-OR ((x1 ∧ x2) ∨ x1)',
    category: 'Mạch điện tử & Bìa K',
    expression: '(x1 ∧ x2) ∨ x1',
    variables: ['x1', 'x2'],
    description: 'Sơ đồ mạch kinh điển trong giáo trình: Cổng AND (x1 ∧ x2) kết hợp với đường rẽ nhánh x1 đưa vào cổng OR cho ngõ ra y = x1 (Luật hấp thụ).',
  },
  {
    id: 'case_and',
    name: 'Mạch 1: Cổng AND 3 ngõ vào (Hội: p ∧ q ∧ r)',
    category: 'Mạch điện tử & Bìa K',
    expression: 'p ∧ q ∧ r',
    variables: ['p', 'q', 'r'],
    description: 'Chỉ có 1 minterm m7 duy nhất (111). Bìa K chỉ có 1 ô đơn lẻ, mạch là 1 cổng AND 3 ngõ vào.',
  },
  {
    id: 'case_or',
    name: 'Mạch 2: Cổng OR 3 ngõ vào (Tuyển: p ∨ q ∨ r)',
    category: 'Mạch điện tử & Bìa K',
    expression: 'p ∨ q ∨ r',
    variables: ['p', 'q', 'r'],
    description: 'Có 7 ô chứa số 1. Bìa K tạo thành 3 nhóm lớn 4 ô lồng nhau. Mạch là 1 cổng OR thu thập tín hiệu.',
  },
  {
    id: 'case_xor',
    name: 'Mạch 3: Cổng XOR Tuyển loại trừ (Cờ caro Bìa K: p ⊕ q)',
    category: 'Mạch điện tử & Bìa K',
    expression: 'p ⊕ q',
    variables: ['p', 'q'],
    description: 'Tạo mẫu cờ caro chéo trên Bìa K không gộp được ô nào: (p ∧ ¬q) ∨ (¬p ∧ q). Mạch gồm 2 NOT, 2 AND, 1 OR.',
  },
  {
    id: 'case_mux',
    name: 'Mạch 4: Bộ chọn kênh Đa hợp 2-to-1 MUX ((¬s ∧ p) ∨ (s ∧ q))',
    category: 'Mạch điện tử & Bìa K',
    expression: '(¬s ∧ p) ∨ (s ∧ q)',
    variables: ['p', 'q', 's'],
    description: 'Mạch chọn kênh kinh điển: khi s=0 truyền p, khi s=1 truyền q. Bìa K chia 2 nhóm 2 ô riêng biệt.',
  },
  {
    id: 'case_corners',
    name: 'Mạch 5: Rút gọn 4 góc vòng biên K-Map 4 biến',
    category: 'Mạch điện tử & Bìa K',
    expression: '(¬p ∧ ¬q ∧ ¬r ∧ ¬s) ∨ (¬p ∧ ¬q ∧ r ∧ ¬s) ∨ (p ∧ ¬q ∧ ¬r ∧ ¬s) ∨ (p ∧ ¬q ∧ r ∧ ¬s)',
    variables: ['p', 'q', 'r', 's'],
    description: 'Chiếm 4 góc biên của Bìa K 4x4 (m0, m2, m8, m10) khép kín vòng tròn và rút gọn thành ¬q ∧ ¬s.',
  },
];
